### ISSUE TITLE
Version number confusion

### ISSUE THREAD

**Issue by suyashjoshi** [tensorflow/java#127]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 0.2.0
- Doc Link: https://www.tensorflow.org/install/lang_java

**Describe the documentation issue**

It's bit confusing to me as I just heard the news about alpha release at version 0.2.0 but when I see the installation docs here https://www.tensorflow.org/install/lang_java it's pointing to maven artifact version 2.3.0 Though the 0.2.0 version is also available on maven central : https://search.maven.org/artifact/org.tensorflow/tensorflow-core-api/0.2.0/jar

Please update the docs so people who want to play with the alpha release can find it.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** No

**Comment by karllessard** [comment]
Thanks @suyashjoshi ,

The SIG has just discussed about this issue and even if the new release is just available as an alpha, we agreed that we need to replace all the existing Java documentation on tensorflow.org and deprecate the previous version. 

We are working on this now and will keep you posted, thank you!

**Comment by suyashjoshi** [comment]
thanks

**Comment by suyashjoshi** [comment]
Just an update that I'm getting this error when executing mvn clean install by following documentation from the official google Tensorflow page:

<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow</artifactId>
  <version>2.3.0</version>
</dependency>

```
[ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project com.example:demo:jar:0.1: Failure to find org.tensorflow:tensorflow:jar:2.3.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by suyashjoshi** [comment]
Also note in the example program section, the POM.xml file has different entry (https://www.tensorflow.org/install/lang_java)

```
<dependency>
      <groupId>org.tensorflow</groupId>
      <artifactId>tensorflow</artifactId>
      <version>1.14.0</version>
    </dependency>
```

**Comment by karllessard** [comment]
This whole page is still about the legacy version that is distributed from [TensorFlow main repository](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java). We will push a new version early this week so that tensorflow.org maintainers can merge it and update the website to promote the new version.

**Comment by karllessard** [comment]
Installation instruction for the new TensorFlow Java have finally been updated on the website (both versions, the new and the legacy one, now coexists until the new version has reached more maturity): https://www.tensorflow.org/install/lang_java

The [API Javadoc](https://www.tensorflow.org/api_docs/java/org/tensorflow/package-summary) replacement present additional challenges and we be updated later.
