### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by xtexChooser** [tensorflow/java#128]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
libtensorflow for x86(e.g. i386/i486/i586/i686)

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
32 bit processor users

**Any Other info.**

**Comment by ohbus** [comment]
I'm willing to set this up and start doing it.
I would just like to know if I would require a 32 bit system for developing this.

**Comment by saudet** [comment]
No, we can compile from a 64-bit host machine. There are a few examples here that we can port from TF 1.x:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/cppbuild.sh

**Comment by xtexChooser** [comment]
> I'm willing to set this up and start doing it.
> I would just like to know if I would require a 32 bit system for developing this.

Look at the comment from saudet(https://github.com/tensorflow/java/issue_comments/709710745_)
You can compile 32 bit binaries from 64-bit host machine.
But I can not compile 64 bit binaries from 32 bit host machine.
