### ISSUE TITLE
Maven can't resolve windows core-api for 0.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#142]
I am trying to use the `0.3.0-SNAPSHOT` release, specifically `tensorflow-core-platform` as is shown in the README.  However, maven can't resolve `org.tensorflow:tensorflow-core-api:jar:windows-x86_64:0.3.0-SNAPSHOT`.  Probably because it's not there, see https://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/tensorflow-core-api/0.3.0-SNAPSHOT/.  Possibly related to there being two linux versions.

**Comment by karllessard** [comment]
Hi @rnett ,

Unfortunately snapshots are not available in windows because we use GitHub actions for building them and the TF build exceeds the 6 hours time limit.

Hopefully we'll get more resources soon from Google so we can unblock this kind of issues.

cc\ @joanafilipa

**Comment by karllessard** [comment]
Ok I rectify, actually non-GPU Windows build should have been deployed successfully according to [GitHub](https://github.com/tensorflow/java/actions/runs/337757118)

I don't know why they have been eradicated from OSS, I've just relaunched the build, normally they should be back in a couple of hours

**Comment by rnett** [comment]
It's working for me now, thanks.
