### ISSUE TITLE
Only having shape and dataType on Output is unintuitive and hard to find

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#146]
I just spent an hour or so trying to figure out how to get the build-time shape of a graph operation.  Had an issue ready to go and everything.  It wasn't until I went poking around in the debugger that I realized it was on Output.  I realize that there are design reasons to separate the output from the op, but `asOutput()` already exists, so I think having `shape()` and `dataType()` default methods on Operation that use `asOutput` is worth it from a usage and discovery standpoint.

**Comment by karllessard** [comment]
I agree, these should be added to the `Operand` interface in fact, with a default implementation that fallbacks to `asOutput().shape()`, for example.

Would you be interested doing it?

**Comment by rnett** [comment]
Yeah, I can handle it.

**Comment by rnett** [comment]
Fixed by #153
