### ISSUE TITLE
how to load tf2 keras model ?

### ISSUE THREAD

**Issue by GerScau** [tensorflow/java#161]
[https://github.com/tensorflow/java/issues/109](url) it seems tensorflow java give up to merge keras module. 

here is a java developer, i used to using session/graph to load tf1 models generate by python. But when i turnto tf2, it drop the session/graph module, so i turn to use keras to trains models.  

now i cannt find any java method on tensorflow/java to load the keras models, also i wonther why session/graph class still could be found on this project, which is drop by tf2 ??

i think there would be people like me, who just want to use java api to use tf2 models, but trains model by python.
appreciate for any help

**Comment by zaleslaw** [comment]
@GerScau What format for Keras model saving are you going to use? h5? json config or yaml? 
One way now is loading graph and variables for inference purposes.
@karllessard correct me if I'm wrong

**Comment by aday00** [comment]
If your Keras model is saved in the latest protobuf format (so you have a *.pb file for your model, and a directory of other metadata from Kera's saved model), which I think is default for TF2, you want to use SavedModelBundle in TensorflowJava to load the Keras model.

I use TensorflowJava from Scala like this, but Java is similar:
```
val saved_model: org.tensorflow.SavedModelBundle = org.tensorflow.SavedModelBundle.load(your_pretrained_model_dirname, "serve")
```
For Java code, read the excellent SavedModelBundleTest.java, which uses SavedModelBundle a lot. https://github.com/tensorflow/java/blob/master/tensorflow-core/tensorflow-core-api/src/test/java/org/tensorflow/SavedModelBundleTest.java

**Comment by karllessard** [comment]
@zaleslaw , I don't think there is a limitation for loading a model for training but I've also only did it for inference so far. 

@GerScau The `SavedModelBundle` only support TF saved model for now, not h5. One known limitation though is that TF Java only support "session centric" models (i.e. these models that only have a single graph), like estimators do, please see more details at the bottom of [this issue](https://github.com/tensorflow/tensorflow/issues/32674).
