### ISSUE TITLE
Create examples directory demonstrating the extent which can be accomplished with this library

### ISSUE THREAD

**Issue by demongolem** [tensorflow/java#218]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

TF 2.3.1
Yes, to the extent possible

**Describe the feature and the current behavior/state.**
There is no examples directory.  There do not appear to be any links from the front page as to how to use it.  I know how to use TF, what I would like to see is what does the code look like in Java and what can (and cannot) be accomplished with this library.

**Will this change the current api? How?**
There will likely be another folder at some level of the hierarchy.  This would call the existing API and would require no new changes to the existing API

**Who will benefit with this feature?**
Anyone who is new to this library. Anyone who spends 99% of their time in Python and doesn't know what it looks like to interact with Tensorflow in Java (or if it is even possible, realistic, or worth one's time.)

**Any Other info.**
Examples would also quickly allow compare/contrast with other alternatives whether it be sticking with Python, using deeplearning4j, or some other product which might exist which would meet the need of deep learning for Java developers

**Comment by Craigacp** [comment]
There are examples in https://github.com/tensorflow/java-models

**Comment by Craigacp** [comment]
It's not as complete as it could be, but open an issue over there with the things you'd like to see and we can figure it out.
