### ISSUE TITLE
Creating Multi-release jar that contains Java 8 and Java 11 classes.

### ISSUE THREAD

**Issue by JimClarke5** [tensorflow/java#220]
I have found a way to create multi-release jar files that contain both Java 8 and Java 11 binaries
 and have tested it with `ndarray`.

You need Java 11 for compilation.
The main source files are under `main/java`.
Specific Java 11 sources and `module-info.java`  are contained under `main/java11.`

This requires changes in the pom.xml for the `maven-compiler-plugin`, for  ndarray:

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>compile-java-11</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <release>11</release>
              <compileSourceRoots>
                <compileSourceRoot>${project.basedir}/src/main/java11</compileSourceRoot>
              </compileSourceRoots>
              <outputDirectory>${project.build.outputDirectory}/META-INF/versions/11</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>compile-java-8</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
              <excludes>
                <exclude>module-info.java</exclude>
              </excludes>
            </configuration>
          </execution>
        </executions>
 </plugin>
```
This works with maven, but when you have 2 versions of the same class, **IntelliJ does not like it**, giving a "Duplicate class found error".  IntelliJ wants you to work with 2 separate IntelliJ modules with the IDE itself doing the merging, but that would create much duplication and violate our current build system reliance on maven.

A Java 11 specific class can exist with the same name in both the Java 8 source tree as well as the Java 11 source tree.
This would allow us to use Java 11 semantics to improve performance in key areas, while keeping support Java 8.
`IllegalRankException` below is my test case for a specific Java 11 class, that also exists in the Java 8 source tree.

The java 11 specific classes are stored in the jar file as: 
```
META-INF/versions/11/
META-INF/versions/11/org/
META-INF/versions/11/org/tensorflow/
META-INF/versions/11/org/tensorflow/ndarray/
META-INF/versions/11/org/tensorflow/ndarray/IllegalRankException.class
META-INF/versions/11/module-info.class
```
The source tree looks like:
```
main/java11
    module-info.java
    org/tensorflow/ndarray/IllegalRankException
```

I want to do more research on the IntelliJ problem with this approach.
How does everyone feel about requiring Java 11 to compile?

**Comment by karllessard** [comment]
A shame (and strange?) that IntelliJ does not support this setup well as it seems to be the proper way for doing it, so I'd suggest we stick to it. 

I'm also fine that we need Java11 to compile the project but there might be a way for be more indulgent for users who still wants to build with Java8, maybe using a Maven Profile activated manually or based on some properties (`java.version` maybe?), in which case we could completely ignore the `src/main/java11` source folder

**Comment by JimClarke5** [comment]
FYI, this compile, though it uses Java 11, creates Java 8 class files from those classes in `main/java`.
I will have to research how to do this, just with Java 8, if we do the multi-release jar in a separate profile.

**Comment by karllessard** [comment]
I don't know what is best, default behavior could be to build TF Java only for your current JDK and activate multi-release on a profile. Or the other way, where we build only for the current JDK if `-Pdev` is set. Whatever you find the easier.

**Comment by Craigacp** [comment]
If we're going to compile the Java 8 bits on Java 11, we should use the `-release 8` flag to avoid issues like this with `Buffer` - https://github.com/microsoft/onnxruntime/issues/6584.

**Comment by Craigacp** [comment]
We baseline on Java 11 now.
