### ISSUE TITLE
Expose is_stateful in ops

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#234]
Op protos have a `is_stateful`, which should be exposed at the instance level in the generated operand classes.  This is needed in function defs as `StatefulPartitionedCall` should be used instead of `PartitionedCall` to call it.

**Comment by Craigacp** [comment]
I guess that's the thing we should use to determine if an op needs a strong or a weak reference in eager session.

**Comment by rnett** [comment]
I've worked around this using the op def list in `TensorFlow`.
