### ISSUE TITLE
Decoding and preprocessing images for use in a saved model created with Python Tensorflow

### ISSUE THREAD

**Issue by pyrator** [tensorflow/java#236]
I have a previously trained Image Classification model, but have problems using this in version 0.2.0 Tensorflow for Java. In order to try and test the Tensor I mocked up a small program to see what values are returned by Tensorflow for a very small and basic image, as well as a comparable Python program. I'm not sure if this is a bug or I'm just doing things wrong.

Sample java code is as follows

[LoadImageTensor.java.txt](https://github.com/tensorflow/java/files/6117088/LoadImageTensor.java.txt)

output is 
`

    Scalar at [0, 0, 0, 0] has value 92
    Scalar at [0, 0, 0, 1] has value 0
    Scalar at [0, 0, 0, 2] has value 116
    Scalar at [0, 0, 1, 0] has value 0
    Scalar at [0, 0, 1, 1] has value 104
    Scalar at [0, 0, 1, 2] has value 0
    Scalar at [0, 0, 2, 0] has value 101
    Scalar at [0, 0, 2, 1] has value 0
    Scalar at [0, 0, 2, 2] has value 107
    Scalar at [0, 1, 0, 0] has value 0
    Scalar at [0, 1, 0, 1] has value 101
    Scalar at [0, 1, 0, 2] has value 0
    Scalar at [0, 1, 1, 0] has value 92
    Scalar at [0, 1, 1, 1] has value 0
    Scalar at [0, 1, 1, 2] has value 46
    Scalar at [0, 1, 2, 0] has value 0
    Scalar at [0, 1, 2, 1] has value 99
    Scalar at [0, 1, 2, 2] has value 0
    Scalar at [0, 2, 0, 0] has value 97
    Scalar at [0, 2, 0, 1] has value 0
    Scalar at [0, 2, 0, 2] has value 114
    Scalar at [0, 2, 1, 0] has value 0
    Scalar at [0, 2, 1, 1] has value 103
    Scalar at [0, 2, 1, 2] has value 0
    Scalar at [0, 2, 2, 0] has value 111
    Scalar at [0, 2, 2, 1] has value 0
    Scalar at [0, 2, 2, 2] has value 92
    image UINT8 (4) tensor with shape [1, 3, 3, 3]

    Scalar at [0, 0, 0, 0] has value 0.0
    Scalar at [0, 0, 0, 1] has value 0.0
    Scalar at [0, 0, 0, 2] has value 0.0
    Scalar at [0, 0, 1, 0] has value 0.0
    Scalar at [0, 0, 1, 1] has value 0.0
    Scalar at [0, 0, 1, 2] has value 0.0
    Scalar at [0, 0, 2, 0] has value 0.0
    Scalar at [0, 0, 2, 1] has value 0.0
    Scalar at [0, 0, 2, 2] has value 0.0
    Scalar at [0, 1, 0, 0] has value 0.0
    Scalar at [0, 1, 0, 1] has value 0.0
    Scalar at [0, 1, 0, 2] has value 0.0
    Scalar at [0, 1, 1, 0] has value 0.0
    Scalar at [0, 1, 1, 1] has value 0.0
    Scalar at [0, 1, 1, 2] has value 0.0
    Scalar at [0, 1, 2, 0] has value 0.0
    Scalar at [0, 1, 2, 1] has value 0.0
    Scalar at [0, 1, 2, 2] has value 0.0
    Scalar at [0, 2, 0, 0] has value 0.0
    Scalar at [0, 2, 0, 1] has value 0.0
    Scalar at [0, 2, 0, 2] has value 0.0
    Scalar at [0, 2, 1, 0] has value 0.0
    Scalar at [0, 2, 1, 1] has value 0.0
    Scalar at [0, 2, 1, 2] has value 0.0
    Scalar at [0, 2, 2, 0] has value 0.0
    Scalar at [0, 2, 2, 1] has value 0.0
    Scalar at [0, 2, 2, 2] has value 0.0
    input_tensor FLOAT (1) tensor with shape [1, 3, 3, 3]
`

Python code is

[testPreprocess.py.txt](https://github.com/tensorflow/java/files/6117070/testPreprocess.py.txt)

Output is 
`
    tf.Tensor(
    [[[255   0   0]
      [255 255 255]
      [  0   0   0]]
    
     [[255 255 255]
      [  0 255   0]
      [255 255 255]]
    
     [[128 128 128]
      [255 255 255]
      [  0   0 255]]], shape=(3, 3, 3), dtype=uint8)
    
    tf.Tensor(
    [[[[1.        0.        0.       ]
       [1.        1.        1.       ]
       [0.        0.        0.       ]]
    
      [[1.        1.        1.       ]
       [0.        1.        0.       ]
       [1.        1.        1.       ]]
    
      [[0.5019608 0.5019608 0.5019608]
       [1.        1.        1.       ]
       [0.        0.        1.       ]]]], shape=(1, 3, 3, 3), dtype=float32)
`

Java Version JDK-14.0.2
Java Tensorflow 0.2.0

System Information:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-K6H6APL
System Manufacturer	Micro-Star International Co., Ltd.
System Model	MS-7C75
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz, 2904 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2.10, 21/05/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	Z490-A PRO (MS-7C75)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume4
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.19041.488"
Username	DESKTOP-K6H6APL\theke
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	17.8 GB
Total Virtual Memory	40.4 GB
Available Virtual Memory	15.9 GB
Page File Space	8.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by pyrator** [comment]
In the meantime I've taken another approach. For anyone interested here's how I accomplished it in 0.2.0.
[LoadImageTensor.java.txt](https://github.com/tensorflow/java/files/6140176/LoadImageTensor.java.txt)
 
and also my code to test my model 
 
[LoadBirdsearchModel.java.txt](https://github.com/tensorflow/java/files/6140182/LoadBirdsearchModel.java.txt)

**Comment by Craigacp** [comment]
I have a quick look through the first code example and it looks like you're feeding the tensor in the wrong way. You should fetch the output of the decodeJpg op, not feed it an image. So instead of `runner.addTarget(decodeImage).feed(decodeImage.asOutput(), image).run()` you'd do `runner.fetch(decodeImage)` because the filename is a constant and passed into readfile which passes it into decodeJpeg.

However we should probably look at the extracted types of the ops as they should probably accept byte arrays not strings. @karllessard what do you think?

**Comment by pyrator** [comment]
Thanks for that. I remember trying different variations and seeing anything sensible. It will be interesting to see if 0.3.0 manages it differently, or perhaps wait for 0.4.0?

**Comment by Craigacp** [comment]
I think this flow will be pretty similar in 0.3.0 and probably 0.4.0 (though we've not settled on the roadmap for that yet), as the model level API isn't finished.

**Comment by pyrator** [comment]
I think I've figured it now and converted to 0.3.0 - hope it helps other people
[LoadImageTensorv3.java.txt](https://github.com/tensorflow/java/files/6144707/LoadImageTensorv3.java.txt)
Thanks for your help, it got me on the right track

**Comment by Craigacp** [comment]
You shouldn't need to do the `asRawTensor().data()` dance, you should be able to directly cast the output to `TFloat32` (as it returns a `TFloat32` instance, but the type system just knows it's a `Tensor`). But other than that it looks ok.

**Comment by pyrator** [comment]
Oh yeah gotcha. Thanks so much. This all helped with cropping and resizing images as well as my model requires 299 x 299
This is more of a hobby for me but I'm willing to share what I've learned if anyone is interested
[LoadBirdsearchModel.java.txt](https://github.com/tensorflow/java/files/6157226/LoadBirdsearchModel.java.txt)
.

**Comment by karllessard** [comment]
We are planning to migrate the examples in the `java-models` repo in the next future. Meanwhile, please refer to the [migration guide](https://github.com/tensorflow/java/blob/master/MIGRATING.md) to learn more about the breaking changes between the different alpha releases.

**Comment by pyrator** [comment]
Thanks @karllessard  - I've refactored my code so it's 0.3.0 compliant and self contained with the exception of  the saved model itself and any test images. I'll wait until you've migrated those examples
