### ISSUE TITLE
The method create(float[][][][]) is undefined for the type Tensor (tensorflow-core-api version 0.3)

### ISSUE THREAD

**Issue by micosacak** [tensorflow/java#258]
I am trying to convert an image to Tensor. For that first I convert the buffered image to float[][][][] array as below.
`File inputImage = new File(inputName);
        BufferedImage bufferedImage = ImageIO.read(inputImage);
        int imgHeight = bufferedImage.getHeight();
        int imgWidth = bufferedImage.getWidth();
        int numberOfChannels = bufferedImage.getTransparency();
        float[][][][] floatImage = new float[1][imgHeight][imgWidth][numberOfChannels];
        for(int i = 0; i < imgHeight; i++) {
        	for(int j = 0; j < imgWidth; j++) {
        		for(int k = 0; k < numberOfChannels; k++) {
        			floatImage[0][i][j][k] = (float) (bufferedImage.getData().getSample(i, j, k)/255.0);
        		}
        	}
        }`
Then, I try to convert the float array to Tensor using `Tensor inputTensor = Tensor.create(floatImage)`.

Is there a way to convert an buffered image to Tensor? I am using ´tensorflow-core-api´ version ´0.3´.

Note: Converting the buffered as above takes longer, maybe there is a faster way to do it in Java.

**Comment by karllessard** [comment]
Yes, you need to convert your float array to a [`NdArray`](https://github.com/tensorflow/java/blob/r0.3/ndarray/src/main/java/org/tensorflow/ndarray/NdArray.java) using the [`StdArrays`](https://github.com/tensorflow/java/blob/r0.3/ndarray/src/main/java/org/tensorflow/ndarray/StdArrays.java) utilities, before initializing a tensor with it, i.e. 
```
TFloat32.tensorOf(StdArrays.ndCopyOf(floatImage));

**Comment by micosacak** [comment]
Thank you very much solved the problem!

**Comment by karllessard** [comment]
Sorry, clicked "enter" too fast. So that being said, there are more efficient ways to do this. For example, you could allocate your float tensors right away and copy the buffered image into it, without passing by a standard array, since you already know the shape of it:

```
TFloat32 t = TFloat32.tensorOf(Shape.of(1, imgWidth, imgHeight, numberOfChannels), data -> {
    // loop in your BufferedImage and initialize the tensor calling data.setFloat(pixelColor, idx...)
});
```

There should be also a way to convert directly your `BufferedImage` to a `FloatDataBuffer` that can directly be passed to initialize the tensor using [this factory](https://github.com/tensorflow/java/blob/2e8f00c2f95fee75f38614ccacb665f0eb5f3250/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/types/TFloat32.java#L89) but pixel colors must be in the right order and normalized accordingly.

**Comment by karllessard** [comment]
> Thank you very much solved the problem!

No problem! BTW, 0.3.1 has been released, you should probably use this version now.

**Comment by micosacak** [comment]
Thanks I will use it. But now I have problem with loading

**Comment by karllessard** [comment]
Let's try to fix it quickly before reopening an issue.

Please  make sure to follow the [instructions](https://github.com/tensorflow/java#using-maven-artifacts) for adding TF to your dependencies. Especially make sure that you don't only depend on `tensorflow-core-api` but also one of its native archive.

A good trick is to simply depend on a platform that will import everything for you, e.g.

```

<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow-core-platform</artifactId>
  <version>0.3.1</version>
</dependency>
```

**Comment by micosacak** [comment]
Finally, I could manage the first step in loading the model and predicting the image in Java! Thank you very much!

I reported the problem here (https://github.com/tensorflow/java/issues/259) as well, now I will close it.
