### ISSUE TITLE
How to concatenate two tensors in NdArray and to convert them to image for saving or printing?

### ISSUE THREAD

**Issue by micosacak** [tensorflow/java#262]
I am not sure if we can ask this kind of questions. I think the way I am processing an array in Python and then saving it as image. I am not sure how to process this in Java especially concatenating the tensors and then converting them to image. If we are not allowed to ask such questions please let me know I will be more careful while opening a new issue.

Here is what I want to do;

`TFloat32 inputTensor = TFloat32.tensorOf(StdArrays.ndCopyOf(floatImage));` the shape of the `floatImage` is [1][128][128][1]. 
Now after loading the model and prediction:
`TFloat32 outputTensor = (TFloat32) sess.runner().feed("serving_default_inputTensor", inputTensor)
        		.fetch("StatefulPartitionedCall")
        		.run()
        		.get(0);`

the shape of `outputTensor` is [1][128][128][2].

Now I want to concatenate inputTensor and outputTensor to get `finalTensor` which has the shape of [1][128][128][3].

**Finally and most important question is how to convert the tensor to an image directly and saving as PNG maybe by ImageIO.write().**

**Comment by micosacak** [comment]
BTW, here is how I converted to float array;

` float[][][][] floatResult = StdArrays.array4dCopyOf(tt);
        for(int i = 0; i < 128; i++) {
        	for(int j = 0; j < 128; j++) {
        		floatResult[0][i][j][0] = floatResult[0][i][j][0]*255;
        		floatResult[0][i][j][1] = floatResult[0][i][j][1]*255;
        	}
        }
        System.out.println(floatResult[0][0][0][1]);
        float[][][] nwimage = new float[128][128][3];
        for(int i = 0; i < 128; i++) {
        	for(int j = 0; j < 128; j++) {
        		nwimage[i][j][0] = floatImage[0][i][j][0];
        		nwimage[i][j][1] = floatResult[0][i][j][0];
        		nwimage[i][j][2] = floatResult[0][i][j][1];
        		
        	}
        }`
but this a long way to concatenate the result.

**Comment by rnett** [comment]
You're probably better off asking in the [gitter](https://gitter.im/tensorflow/sig-jvm) since it's more help than an issue, but it's not a big problem.

The `Ops` class maps pretty closely to the Python API, so you can find the appropriate Python function ([concat](https://www.tensorflow.org/api_docs/python/tf/concat)) and it will be there in Ops.  The Javadocs aren't easily accessible yet but they will be.

Now, you're dealing with Tensors rather than operands, but you can create an eager session (or use the default), load the tensors into it with `Ops.constantOf()`, and then use tensorflow operations.  You can get the result tensors from the eager operands using `asTensor()`.

To save it, you'll like have to convert it back to float arrays manually, then use whatever library.  I'm not aware of a better alternative at the moment.

**Comment by micosacak** [comment]
Thanks. I was asking if there is a direct way from Tensor to Image. Then, I will continue from the float array.

I will use gitter for these kind of questions.

**Comment by Craigacp** [comment]
You can iterate the tensor object and call `setRGB` on a `BufferedImage` and then write that out using `ImageIO`. Underneath the `TFloat32` is a `FloatNdArray` that has iteration methods with indices on them.

**Comment by micosacak** [comment]
Thanks, I first convert all tensor to float array then converted the float array to Buffered Image. [Here is code](https://stackoverflow.com/questions/66864580/how-to-convert-double-array-to-image-in-java-ro-save-as-image/66879712#66879712)

**Comment by pyrator** [comment]
I'm working my way through some of this too but you can multiply a tensor by 255 like this. I haven't tried concatenating yet

```
    /**
     * Multiply tensor by 255
     * @param tFloat32Tensor original tensor with values 0 - 1
     * @return tensor with values 0 - 255
     */
    private static TFloat32 reprocessImagesNoReshape(TFloat32 tFloat32Tensor) {
        Ops tf = Ops.create();
        return tf.math.mul(
                tf.constant(tFloat32Tensor),
                tf.constant(255.0f)
        ).asTensor();
    }
```

I haven't got my side working yet but there are also EncodeJpeg,  EncodePng etc. operations
I think they might work like this but I think I'm still testing stuff

```
    EncodeJpeg.Options ejoptions = EncodeJpeg.quality(100L);
    EncodeJpeg encodeJpeg = tf.image.encodeJpeg(tf.constant(singleTUint8), ejoptions);
```
