### ISSUE TITLE
LeakyReLU activation function

### ISSUE THREAD

**Issue by micosacak** [tensorflow/java#293]
I wonder if there is `LeakyReLU` as activation function in tensorflow/java. I check [here](https://github.com/tensorflow/java/tree/master/tensorflow-framework/src/main/java/org/tensorflow/framework/activations) but it is not among the activation functions.

**Comment by Craigacp** [comment]
A `LeakyReLU` is a `ReLU` with a positive alpha value, and the threshold set to zero. So you can use the `ReLU` class in tensorflow-java for that. The Keras one is a wrapper around ReLU and we've not got around to building out that kind of convenience wrapper yet.

**Comment by micosacak** [comment]
Thanks!
