### ISSUE TITLE
Using object detection saved model in Java

### ISSUE THREAD

**Issue by Daboudette** [tensorflow/java#294]
Hi everyone :) 

I have trained a faster RCNN model with python tensorflow 2.0 (Object detection API : https://github.com/tensorflow/models/tree/master/research/object_detection). So now I have a saved model :
![image](https://user-images.githubusercontent.com/80925335/115525945-d99e8600-a28f-11eb-9325-c46d9813912e.png)
In saved_model/ :
![image](https://user-images.githubusercontent.com/80925335/115526019-ea4efc00-a28f-11eb-84c7-67e5ee6a1713.png)

I would like to use it in Java. Do you know : 
- if the model can be used like this in Java,
- how to load the model in Java,
- how to correctly transform image to Tensor in Java ?

Thanks a lot,

Claire

**Comment by Craigacp** [comment]
There is an example of using a FasterRCNN in the TensorFlow [java-models repo](https://github.com/tensorflow/java-models/tree/master/tensorflow-examples/src/main/java/org/tensorflow/model/examples/cnn/fastrcnn). It's still being worked on, but you should be able to get the information you need from that sample.

**Comment by Daboudette** [comment]
Thanks @Craigacp ! We have tried that. But, the results for the same test images are not the same in Java than in Python. The performance of the model in Java is quite bad, while in Python the results are really good.

**Comment by Craigacp** [comment]
Could you post the Java code you are using?

**Comment by Daboudette** [comment]
I can't because it's from my company :( 
But we finally use the same code as follow : https://github.com/tensorflow/java-models/blob/master/tensorflow-examples/src/main/java/org/tensorflow/model/examples/cnn/fastrcnn/FasterRcnnInception.java
It looks like we can't use these models in java..

**Comment by Craigacp** [comment]
At inference time TF Java has the same view of your model that TF Serving would, so if it works there it should work in TF Java. It's all handled by the native TF library. How are you presenting the input to the model, and what's the failure mode of test images (is it not finding expected objects, are the bounding boxes off, does it find anything at all etc)?

**Comment by Daboudette** [comment]
@Craigacp I'm going to ask to my colleague how he is presenting the input to the model ! 
The model is for detecting screen of a specific object. On an image there is at least one screen to detect.
Here's the problem : 
In python it's perfect !
In Java : 
- the model doesn't detect well the object : the bounding boxe with the best score are in the image but in middle of nowhere
- even if the bounding boxe is correct, the score is really low (50% or less with java vs 99% in python)

**Comment by karllessard** [comment]
Hi @Daboudette , I agree with @Craigacp , it probably has to do with the I/O operations happening before/after running the model. When it comes to inference, everything is happening in the C++ core, no matter if you started from Java or Python.

**Comment by Daboudette** [comment]
Hi everyone. We have found the problem. There was a problem when we were loading images. Thanks for your help everyone :)
