### ISSUE TITLE
Converting Buffered Images to Tensors

### ISSUE THREAD

**Issue by phydesmith** [tensorflow/java#309]
I am trying to use TF for object detection ( have trained and exported a model via the python API ). I have a javafx app that I've built that I'm trying to incorporate the inference into, it screenshots the game I'm playing in real time. My plan is to run inference on the screenshots (BufferedImages) and display the bounding boxes in real time as well. 

I am getting an error:

>  Can only copy to arrays of the same shape ([1228800] != [1, 640, 640, 3])

based on the following code:

```
    private Tensor processImage(BufferedImage image){
        BufferedImage formattedImage = convertBufferedImage(image, BufferedImage.TYPE_3BYTE_BGR);
        final byte[] data = ((DataBufferByte) formattedImage.getData().getDataBuffer()).getData();
        bgr2rgb(data);
        final long BATCH_SIZE=1;
        final long CHANNELS=3;
        Shape shape = Shape.of(
                        BATCH_SIZE,
                        formattedImage.getHeight(),
                        formattedImage.getWidth(),
                        CHANNELS);
        return TUint8.tensorOf(shape, values -> StdArrays.copyTo(data, values));
    }
```

which was adapted from:

```
     private Tensor<UInt8> makeImageTensor(BufferedImage image) throws IOException {
        BufferedImage formattedImage = convertBufferedImage(image, BufferedImage.TYPE_3BYTE_BGR);
        byte[] data = ((DataBufferByte) formattedImage.getData().getDataBuffer()).getData();
        bgr2rgb(data);
        final long BATCH_SIZE = 1;
        final long CHANNELS = 3;
        long[] shape = new long[] {BATCH_SIZE, formattedImage.getHeight(), formattedImage.getWidth(), CHANNELS};
        ByteBuffer byteBuffer = ByteBuffer.wrap(data);
        data = null;
        return Tensor.create(UInt8.class, shape, byteBuffer);
    }
```
(source: https://github.com/davpapp/PowerMiner/blob/master/src/ObjectDetector.java)
Supposedly this was adapted from a different example that is no longer available. 

I have gone through a bunch of the documentation and guides to try and figure this out, but it seems like examples from a year or two ago use Tensor<UInt8> but it now is supposed to not have that type? I'm a bit confused on how to use this so any help would be appreciated (even if it's just pointing me to a different and more up to date example).

**Comment by phydesmith** [comment]
Ok, if anyone else had an issue, I just hand coded this into a 4d byte array and fed it into the copyto method.

**Comment by Craigacp** [comment]
You should be able to make an `org.tensorflow.ndarray.buffer.DataBuffer` using `DataBuffers.of(byte[])` and then feed that into the `TUint8.tensorOf(shape,buffer)`. I'm not sure if you'll get the data out of the buffered image in the necessary format though. For TF it should be in row major order.

Using a 4d byte array is going to be slow as Java multidimensional arrays require a lot of pointer chasing, but if you've got to rearrange it anyway then there isn't much else to do.
