### ISSUE TITLE
2.1?

### ISSUE THREAD

**Issue by Jie-Yuan** [tensorflow/java#32]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by Jie-Yuan** [comment]
tf2.1 pb

**Comment by karllessard** [comment]
Hi @Jie-Yuan , can you please be more explicit on your demand? Thank you

**Comment by tastyminerals** [comment]
The README does not provide any information on what version of TF does this java api support. Is it for TF2.0, TF2.1, or earlier versions?

**Comment by Craigacp** [comment]
Currently the API targets TF 2.2 rc2.

**Comment by karllessard** [comment]
I've added [this section](https://github.com/tensorflow/java/blob/master/README.md#tensorflow-version-support) to the README.md
