### ISSUE TITLE
Help!!! JVM crash

### ISSUE THREAD

**Issue by 729222507** [tensorflow/java#349]
**project start log:**

- A fatal error has been detected by the Java Runtime Environment:
- SIGILL (0x4) at pc=0x00007f1d77a496d0, pid=193, tid=0x00007f1e2d43b700
- JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
- Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
- Problematic frame:
- C  [libtensorflow_framework.so.2+0x160d6d0]  nsync::nsync_mu_init(nsync::nsync_mu_s_*)+0x0
- Core dump written. Default location: /home/core or core.193
- An error report file with more information is saved as:
- /home/hs_err_pid193.log`

**hs_err_pid193.log:**
![image](https://user-images.githubusercontent.com/5824535/124743962-d478db00-df50-11eb-88af-a8e588033fd2.png)

**Comment by Craigacp** [comment]
Can you post the full stack trace? What were you trying to do when it crashed?

**Comment by karllessard** [comment]
I'll add to @Craigacp 's list, which version of TF Java are you using? Can you try whatever you are doing with the latest snapshot (0.4.0-SNAPSHOT) and see if it still crashes?

**Comment by saudet** [comment]
Seems to be a bug in nsync and/or devtoolset:
https://stackoverflow.com/questions/64408047/illegal-instruction-0x00007ffff3712210-in-nsyncnsync-mu-initnsyncnsync-mu

**Comment by 729222507** [comment]
It's OK to run on a physical machine, but not in docker。Compared with the running environment,I think it's probably caused by the instruction set .[docker :amd46，tensorflow-core-api : linux-x86_x64]

**Comment by Craigacp** [comment]
You should be able to compile from source and specify the instructions available on your docker host. I think by default the newest thing we target is AVX, so presumably that's missing in your docker environment.

**Comment by 729222507** [comment]
Confirm the instruction set, the host of the JVM crash does not support AVX, avx2, FMA instruction set, and it starts normally after changing one. Thank you
