### ISSUE TITLE
Bug in String deallocation

### ISSUE THREAD

**Issue by brychcy** [tensorflow/java#357]
When trying to upgrade to 0.3.1 we got junit failures in a class with multiple
tests that load and use saved models with string inputs and outputs.

Tensorflow was for some tests throwing an exception with a message that definitely was wrong.

When the tests were run individually, no error occured.

When the tests were reordered, different tests were failing.

So this smells likely a memory corruption, and I've looked at the changes in  0.3.1 (w.r.t. 0.3.0),
namely #253.

I think I've understood the issue: The problem appears if the underlying TensorBuffers are shared, in which case
the strings should not be deallocated.

I'll send a PR which uses TF_TensorMaybeMove (which in its current implementation returns null if then TensorBuffer is shared, and the tensor itself, if it is not) to detect and avoid the situation (the PR fixes the problem for us)

**Comment by brychcy** [comment]
See PR #358

**Comment by karllessard** [comment]
Thanks for the PR @brychcy , we'll take a look at it.

Can you also please retry with 0.3.2, which was released a few weeks ago? We have fixed a memory leak related to loading/unloading saved models, that might prevent other issues as well

**Comment by brychcy** [comment]
Happens also with 0.3.2.
Actually I directly tried to upgrade to that but then noted that the problem already appears with 0.3.1.

**Comment by brychcy** [comment]
This has been fixed on the master and in 0.3.3 so this bug can be closed
