### ISSUE TITLE
Bug with method copyTo - Method copyTo not working on Tensor that is output from a TF model

### ISSUE THREAD

**Issue by cor3ntino** [tensorflow/java#367]
Hello,
I am having an issue with copying a Tensor (output of my model) into an NdArray, to be able to read the values of this output tensor.

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04.2 LTS, x86-64
- TensorFlow built with sbt from "org.tensorflow" % "tensorflow-core-platform" % "0.3.2"
- TensorFlow version: 2.4.1 (but also tried with TF1.x)
- Java version: Java 8 (openjdk version "1.8.0_292"), but I also tried with Java 11 and I have the same issue

**Describe the current behavior**

I want to get the output of a model, previously trained in Python, and read its values. To do so, I create a random float tensor with the shape of my normal inputs (batch, 100, 200) and I pass it through the model; as a result, I get an int tensor of shape (batch, 100). For now everything is perfectly normal.
Then, I want to read the values in the tensor. To do so, I use method copyTo to copy the data of my output tensor into an array; but, such method does not work on my output tensor; even though it is a Tensor of the TF lib.

What is especially weird is that:
- the model outputs the right shape of tensor with the right data type (int), so I suppose it is working as well as it was in Python.. and there is no particular reason it doesn't since I saved it with TF2 lib in Python and load it with TF2 lib in Java
- I tested to use method copyTo with random Tensors of float and int and it worked correctly; it just doesn't work with the tensor that is output by the model
- my output tensor is of the same type as the other tensors I created, as you can see below, and yet the error I get looks like such tensor is not recognized as a Tensor and thus, cannot be applied copyTo method. However, when I check for the type, it turns out that it is indeed a TF Tensor.

The code basically do this:
- load a TF model and get its signature definition
- create a random array of dimension (2, 100, 200) and create a Tensor from it --> it will be my inputTensor
- (just verify I can transform this inputTensor back to an array with method copyTo)
- create a Tensor outputTensor by passing the inputTensor into the loaded model
- try to copy the data of outputTensor into an array to be able to read its values

**Code**

    import java.util.List;
    import java.util.Random;

    import org.tensorflow.Tensor;
    import org.tensorflow.TensorFlow;
    import org.tensorflow.SavedModelBundle;
    import org.tensorflow.proto.framework.SignatureDef;
    import org.tensorflow.types.TFloat32;
    import org.tensorflow.types.TInt32;
    import org.tensorflow.ndarray.Shape;
    import org.tensorflow.ndarray.NdArrays;
    import org.tensorflow.ndarray.FloatNdArray;
    import org.tensorflow.ndarray.IntNdArray;
    import org.tensorflow.Session;

    public class TestClassifier {

        public static void main(String args[]) {

            String working_dir = System.getProperty("user.dir");
            String dir = working_dir + "/training-python/model_TensorFlow";

            SavedModelBundle model;
            try {
                model = SavedModelBundle.load(dir, "serve");
            } catch (Exception e) {
                System.out.println("Problem loading tensorflow model");
                System.out.println(dir);
                System.out.println(e.getMessage());
                throw new RuntimeException(e);
            }

            SignatureDef signatureDef = model.metaGraphDef().getSignatureDefMap().get("serving_default");
            System.out.println(signatureDef);

            String inputOperation = signatureDef.getInputsMap().get("input_1").getName();
            String outputLocation = signatureDef.getOutputsMap().get("crf").getName();

            Shape shape_input = Shape.of(2, 100, 200);

            FloatNdArray data = NdArrays.ofFloats(shape_input);

            Random r = new Random();
            for (int k=0; k<2; k++) {
                for (int i=0; i<100; i++) {
                    for (int j=0; j<200; j++) {
                        data.setObject(-1 + r.nextFloat() * 2, k, i, j);
                    }
                }
            }

            TFloat32 inputTensor = TFloat32.tensorOf(data);
            System.out.println(inputTensor);
            System.out.println(inputTensor.shape());
            
            // Verify it is possible to copy this input Tensor to an NdArray
            FloatNdArray resultMatrix = NdArrays.ofFloats(shape_input);
            inputTensor.copyTo(resultMatrix);

            Tensor outputTensor = model.session().runner()
                .feed(inputOperation, inputTensor)
                .fetch(outputLocation)
                .run()
                .get(0);
            System.out.println(outputTensor);
            System.out.println(outputTensor.shape());

            Shape shape_output = Shape.of(2, 100);
            
            // Try to copy this output Tensor to an NdArray
            IntNdArray resultMatrix2 = NdArrays.ofInts(shape_output);
            outputTensor.copyTo(resultMatrix2);

When I just check for the types of inputTensor and outputTensor (without the 2 last lines of code), I find no error

![image](https://user-images.githubusercontent.com/40430314/129334102-3f5dcf08-5b14-4a90-85b1-9f29c4f66eca.png)

However, when trying to copy the data of outputTensor into an array, I get the following error; as if it did not recognize that outputTensor was of Tensor type

![image](https://user-images.githubusercontent.com/40430314/129331672-e7d8940a-6a95-4b7c-8104-521fb6ead1f0.png)

Do you believe there is an issue with using copyTo method on an output Tensor?

**Comment by karllessard** [comment]
Thanks for the @cor3ntino , `copyTo` should be available from any tensors, including those coming as an output of a model inference. I'll try to replicate the issue and come back to you after.

**Comment by cor3ntino** [comment]
Hello @karllessard!
Thank you for helping

**Comment by karllessard** [comment]
@cor3ntino , can you try to cast your output tensor to the right tensor type before calling `copyTo`? If you are working directly with `Tensor`, the compiler won't know that it is a tensor of ints, therefore that it can accept an `IntNdArray` in parameter. Please try to do something like this and let us know if that worked (note that I'm protecting output tensors with a try-with-resource block, that's also important to do, even with other TF resources such a the input tensors and the graph, see Javadoc):

```java
try (TInt32 outputTensor = (TInt32) model.session().runner()
            .feed(inputOperation, inputTensor)
            .fetch(outputLocation)
            .run()
            .get(0)) {
        System.out.println(outputTensor);
        System.out.println(outputTensor.shape());

        Shape shape_output = Shape.of(2, 100);
        
        // Try to copy this output Tensor to an NdArray
        IntNdArray resultMatrix2 = NdArrays.ofInts(shape_output);
        outputTensor.copyTo(resultMatrix2);
}
```

**Comment by cor3ntino** [comment]
Thank you for your answer @karllessard, indeed it works with casting before calling `copyTo`! I did not think about that because it looked like the type of my Tensor was correct. Thank you very much!
Alright, I will take care of my code by using try-with-resource blocks!
Thanks a lot for your advice ;)

**Comment by tobidelbruck** [comment]
This thread does not apply to TF2 tensorflow java, since Tensor (and it's subtypes) do not have copyTo() method anymore. I have not yet figured out replacement.

**Comment by Craigacp** [comment]
What version are you using? TF-Java 1.0 is still built on top of tensorflow-java-ndarray which supplies the copyTo and copyFrom methods. We did rename a few things in the ndarray package before that hit 1.0 for consistency, but this should be the same.
