### ISSUE TITLE
Is there any way to use different gpu in multiple sessions?

### ISSUE THREAD

**Issue by Pekary** [tensorflow/java#380]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.4
- Are you willing to contribute it (Yes/No): Yes if someone has ideas.

**Describe the feature and the current behavior/state.**
I use saved_model recommended by tf2.x to persist my model. current `ConfigProto` is per-process, it will raise error when i use different gpu in multiple sessions. I find the [link](https://github.com/tensorflow/tensorflow/issues/19083) provides a way of modifying GraphDef on a frozen model, but it seems no way to use `SavedModelBundle` for utilizing different gpu in multiple sessions. I also find virtual device settings is per-process.

**Will this change the current api? How?**
I think it should not.

**Who will benefit with this feature?**
it has been long times since this [issue](https://github.com/tensorflow/tensorflow/issues/19083) is posed in tf1, and the issue is still concerned by someone who used tf2.
**Any Other info.**

**Comment by Craigacp** [comment]
I still don't think this is supported by the core TF runtime, as you mention the core data structures are per process not per session or context. Uber hacked around it (https://github.com/uber/neuropod/pull/487), which I'd be reluctant to do in TF-Java as it would interact poorly with our goal of building a Java API equivalent of the Python API. I think this is deeply baked into TF (e.g. https://github.com/tensorflow/tensorflow/issues/27114 among other issues which mention it).

I'd recommend raising an issue on the core TensorFlow repo as this is out of our control.

**Comment by Pekary** [comment]
ok, i'll try the Uber's workaround, thanks!
