### ISSUE TITLE
Any plan on deploy tensorflow 2.x

### ISSUE THREAD

**Issue by ericxsun** [tensorflow/java#40]
Tensorflow 2.1 has been released in the [main repository](https://github.com/tensorflow/tensorflow). So,  any plan for releasing a new version (2.x) of the java package?

**Comment by Craigacp** [comment]
The first release out of this repository will target TF 2.2, once we've finished with the various refactorings. It will have support for training and parts of TF's dataset API, in addition to the features already present in the 1.15 version of the Java API. It's likely to have an independent version number from the TF release it supports similar to the other TF bindings like Swift and JavaScript.

**Comment by karllessard** [comment]
I've added [this section](https://github.com/tensorflow/java/blob/master/README.md#tensorflow-version-support) in the README file to keep track of the version we are currently supporting.

**Comment by ericxsun** [comment]
tensorflow-2.2 has been released, so i'm wondering when to release tf-2.2-java?

**Comment by karllessard** [comment]
I’m working on this at the same time that I’m trying to fix [the issue](https://github.com/tensorflow/java/issues/43) with custom ops, shouldn’t take to long
