### ISSUE TITLE
Missing tensorflow-core-platform-mkl:0.4.0 on maven central

### ISSUE THREAD

**Issue by adaussy** [tensorflow/java#408]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04 x86\_64): Windows 10 x64
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.4.1
- Java version (i.e., the output of `java -version`): 11
- Java command line flags (e.g., GC parameters):
- Installed from Maven Central?: Yes
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I was wondering why I could not find tensorflow-core-platform-mkl:0.4.0 on maven central. 
Is this platform not maintained anymore? Or maybe it was simply forgotten?

**Comment by karllessard** [comment]
Hi @adaussy , 

We (SIG JVM) have deliberately stopped to maintain and distribute MKL-enabled artifacts starting from 0.4.0, as their builds on the newest versions of TF were continuously getting less stable and many users were not actually seeing any gain in performance when using them (or even worst, observed a significant drop).

You can still try to build and try it by your own by following [these instructions](https://github.com/tensorflow/java/blob/master/CONTRIBUTING.md)

**Comment by adaussy** [comment]
Good to know.

Thanks for your answer and the great library!

Regards,

Arthur
