### ISSUE TITLE
TF 2.x Java Binding @rpath/libtensorflow_framework.1.dylib 

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/java#43]
OS Platform and Distribution : macOS Catalina 10.15.3

TensorFlow installed from : binary

TensorFlow version : 2.1.0

Python version: 3.7.3

Java - 1.8

So basically I am using TF 1.15.0 Java binding to do the inferencing from savedmodel where features are ported as part of savedmodel , the code below is working 

```
import org.tensorflow.SavedModelBundle;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;

public class TF1_b {

	public static void main(String[] args) {

		String testSen = "1";

		byte[] inputBytes = new byte[1];
		try {
			inputBytes = testSen.getBytes("UTF-8");
		} catch (Exception e) {
			e.printStackTrace();
		}

		System.out.println(TensorFlow.version());


		String basePath = "<path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/";
		System.load(basePath + "_wordpiece_tokenizer.dylib");


		try (SavedModelBundle b = SavedModelBundle.load("<saved_model_path>", "serve")) {


			Session sess = b.session();


			Tensor x = Tensor.create(inputBytes, String.class);

			float[][] y = sess.runner().feed("text:0", x)
							.fetch("linear/linear_model/linear_model/linear_model/weighted_sum:0").run().get(0)
							.copyTo(new float[1][1]);

			System.out.println(y[0][0]);



		} catch (Exception e) {
			System.out.println(e);

		}
	}

}

```

In pom.xml the dependency I am using for above is 

```
<dependencies>
		<dependency>
			<groupId>org.tensorflow</groupId>
			<artifactId>tensorflow</artifactId>
			<version>1.15.0</version>
		</dependency>
	</dependencies>
```
The above code works perfect and i am able to load `System.load(basePath + "_wordpiece_tokenizer.dylib");` with no problems .

Now when I try to run the same model with 
```

<repositories>
    <repository>
        <id>tensorflow-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
<dependencies>
    <!-- Example of dependency, see README.md for more options -->
    <dependency>
        <groupId>org.tensorflow</groupId>
        <artifactId>tensorflow-core-platform</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </dependency>
</dependencies>
```
as described [https://stackoverflow.com/questions/61373396/tensorflow-2-x-java-bindings](https://stackoverflow.com/questions/61373396/tensorflow-2-x-java-bindings) 

with changes only for for two lines 

```
Tensor x = TString.scalarOf(new String("1"));
Tensor<TFloat32> y = sess.runner().feed("text:0", x) .fetch("linear/linear_model/linear_model/linear_model/weighted_sum:0").run().get(0).expect(TFloat32.DTYPE);
```
I get error 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: <path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib: dlopen(<path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib, 1): Library not loaded: @rpath/libtensorflow_framework.1.dylib
  Referenced from: <path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
```

The path `<path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib:` exists and so TF 1.15.x  java inferencing is working fine for inferencing .

The java code for TF 2.x  i am using is below 

```

import org.tensorflow.SavedModelBundle;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;
import org.tensorflow.tools.ndarray.NdArrays;
import org.tensorflow.types.TFloat32;
import org.tensorflow.types.TString;

public class TF_2 {



	public static void main(String[] args) {



		String testSen = "1";

		byte[] inputBytes = new byte[1];
		try {
			inputBytes = testSen.getBytes("UTF-8");
		} catch (Exception e) {
			e.printStackTrace();
		}

		System.out.println(TensorFlow.version());

		String basePath = "<path>/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/";

		System.load(basePath + "_wordpiece_tokenizer.dylib");



		try (SavedModelBundle b = SavedModelBundle.load("<saved_model_path>", "serve")) {


			Session sess = b.session();


			Tensor x = TString.scalarOf(new String("1"));

			Tensor<TFloat32> y = sess.runner().feed("text:0", x)
							.fetch("linear/linear_model/linear_model/linear_model/weighted_sum:0").run().get(0)
							.expect(TFloat32.DTYPE);


			System.out.println(y.data().toString());



		} catch (Exception e) {
			System.out.println(e);
		}
	}


}
```

**Comment by saudet** [comment]
`libtensorflow_framework.1.dylib` is not available with TF 2.x.
You'll need to find a version of your custom ops that work with TF 2.x.

**Comment by 17patelumang** [comment]
`_wordpiece_tokenizer.dylib`  is a custom op  from tensorflow_text library https://www.tensorflow.org/tutorials/tensorflow_text/intro that is supported and available in TF 2.x in python , it should support is in java as well ?

**Comment by saudet** [comment]
It should work yes, so use that version for TF 2.x.

**Comment by 17patelumang** [comment]
@saudet my apologies i am not on same page. I am serializing the model to savedmodel format in TF 1.15.x , and when I this model for inferencing on Java TF 2.x it throws error , so you mean to serialize model in TF 2.x itself ? Sorry i am unable to understand the meaning of use that version for TF 2.x

**Comment by saudet** [comment]
Yes, you'll need to do everything in TF 2.x. It's not compatible with TF 1.x.

**Comment by 17patelumang** [comment]
@saudet got it , thank you for reply . Also I am not getting same error when I try to run in TF 1.15.x java binding , so why in TF 1.15.x java binding it doesnot throw error ?

**Comment by 17patelumang** [comment]
@saudet any update ?

**Comment by saudet** [comment]
About what? Like you said, anything that was made with TF 1.x will work with TF 1.x, that is expected.

**Comment by 17patelumang** [comment]
@saudet  my question was my savedModel in TF 1.x works well in java binding for TF 1.x with me doing `System.load(basePath + "_wordpiece_tokenizer.dylib");` however same tf model does not work in TF 2.x java binding with  `System.load(basePath + "_wordpiece_tokenizer.dylib");` , so that is expected behavior correct ?

**Comment by saudet** [comment]
Yes, that's expected.

**Comment by 17patelumang** [comment]
thank you we can close this ticket .

**Comment by karllessard** [comment]
@17patelumang , can you please point me out where you have found the `_wordpiece_tokenizer.dylib` binaries you are using? Directly from the Python packages or you built it yourself?

It's dependency to `libtensorflow_framework.1.dylib` indeed means that it has been built to be executed on a TF1.x version. But I would like to validate that the new version of `tensorflow-text` will effectively work on our TF2.x binaries.

@saudet , FYI, what I would like to validate is if we need to deliver more native libraries in our artifacts that `libtensorflow`. For example, the 1.15 client delivers `libtensorflow_framework` as a separate library, like this:
```
tar tvf ~/Downloads/libtensorflow_jni-1.15.0.jar 
drwxrwxrwx  0 0      0           0 22 Oct  2019 META-INF/
-rwxrwxrwx  0 0      0         254 22 Oct  2019 META-INF/MANIFEST.MF
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/tensorflow/
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/tensorflow/native/
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/tensorflow/native/linux-x86_64/
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/tensorflow/native/windows-x86_64/
drwxrwxrwx  0 0      0           0 22 Oct  2019 org/tensorflow/native/darwin-x86_64/
-rwxrwxrwx  0 0      0      422253 22 Oct  2019 org/tensorflow/native/linux-x86_64/THIRD_PARTY_TF_JNI_LICENSES
-rwxrwxrwx  0 0      0   154073736 22 Oct  2019 org/tensorflow/native/linux-x86_64/libtensorflow_jni.so
-rwxrwxrwx  0 0      0    35226832 22 Oct  2019 org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.1
-rwxrwxrwx  0 0      0       11419 22 Oct  2019 org/tensorflow/native/linux-x86_64/LICENSE
-rwxrwxrwx  0 0      0    78973440 22 Oct  2019 org/tensorflow/native/windows-x86_64/tensorflow_jni.dll
-rwxrwxrwx  0 0      0       11419 22 Oct  2019 org/tensorflow/native/windows-x86_64/LICENSE
-rwxrwxrwx  0 0      0      422253 22 Oct  2019 org/tensorflow/native/darwin-x86_64/THIRD_PARTY_TF_JNI_LICENSES
-rwxrwxrwx  0 0      0    28642820 22 Oct  2019 org/tensorflow/native/darwin-x86_64/libtensorflow_framework.1.dylib
-rwxrwxrwx  0 0      0       11419 22 Oct  2019 org/tensorflow/native/darwin-x86_64/LICENSE
-rwxrwxrwx  0 0      0   284042344 22 Oct  2019 org/tensorflow/native/darwin-x86_64/libtensorflow_jni.dylib
drwxrwxrwx  0 0      0           0 22 Oct  2019 META-INF/maven/
drwxrwxrwx  0 0      0           0 22 Oct  2019 META-INF/maven/org.tensorflow/
drwxrwxrwx  0 0      0           0 22 Oct  2019 META-INF/maven/org.tensorflow/libtensorflow_jni/
-rwxrwxrwx  0 0      0         593 22 Oct  2019 META-INF/maven/org.tensorflow/libtensorflow_jni/pom.xml
-rwxrwxrwx  0 0      0         117 22 Oct  2019 META-INF/maven/org.tensorflow/libtensorflow_jni/pom.properties
``` 
(note that `libtensorflow_jni` is statically linked to `libtensorflow`). But in the new artifacts, only `libtensorflow` is available:
```
tar tvf tensorflow-core-api-0.1.0-SNAPSHOT-macosx-x86_64.jar 
-rwxrwxrwx  0 0      0           0 23 Apr 09:21 META-INF/MANIFEST.MF
drwxrwxrwx  0 0      0           0 23 Apr 09:21 META-INF/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 org/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 org/tensorflow/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 org/tensorflow/internal/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 org/tensorflow/internal/c_api/
drwxrwxrwx  0 0      0           0 23 Apr 09:20 org/tensorflow/internal/c_api/macosx-x86_64/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 META-INF/maven/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 META-INF/maven/org.tensorflow/
drwxrwxrwx  0 0      0           0 23 Apr 09:21 META-INF/maven/org.tensorflow/tensorflow-core-api/
-rwxrwxrwx  0 0      0           0 23 Apr 09:20 org/tensorflow/internal/c_api/macosx-x86_64/LICENSE
-rwxrwxrwx  0 0      0           0 23 Apr 09:20 org/tensorflow/internal/c_api/macosx-x86_64/libjnitensorflow.dylib
-rwxrwxrwx  0 0      0           0 23 Apr 09:20 org/tensorflow/internal/c_api/macosx-x86_64/THIRD_PARTY_TF_JNI_LICENSES
-rwxrwxrwx  0 0      0           0 23 Apr 09:20 org/tensorflow/internal/c_api/macosx-x86_64/libtensorflow.2.dylib
-rwxrwxrwx  0 0      0           0 22 Apr 23:50 META-INF/maven/org.tensorflow/tensorflow-core-api/pom.xml
-rwxrwxrwx  0 0      0           0 23 Apr 01:50 META-INF/maven/org.tensorflow/tensorflow-core-api/pom.properties
```
So if custom op libraries like `tensorflow-text` still builds and links to that smaller library called `libtensorflow-framework` for TF2.x then it will still not work on TF Java 2.x.

**Comment by 17patelumang** [comment]
@karllessard  its coming directly from directly from the Python packages . I haven't build it .

**Comment by Craigacp** [comment]
You should upgrade your copy of tensorflow_text to one compatible with tf2. Running `pip install tensorflow_text` just now gave me version 2.1.1, which had a wordpiece library which binds to TF 2.

```
$ otool -L tf-2//lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib
tf-2//lib/python3.7/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib:
	bazel-out/darwin-opt/bin/tensorflow_text/python/ops/_wordpiece_tokenizer.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.6.0)
	@rpath/libtensorflow_framework.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1670.10.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

**Comment by 17patelumang** [comment]
@Craigacp thank you reply , i cannot upgrade TF 2.x directly since we are using TF 1.15.x as of now  , so i am using this `System.load` in java to do point to that `.dylib` file to use the binary

**Comment by 17patelumang** [comment]
do we have any other solution for using tensorflow_text in TF 1.15.x ?

**Comment by karllessard** [comment]
> @rpath/libtensorflow_framework.2.dylib

So if we do not distribute that library in our artifacts, it won't work... so we need to add it, like it was in TF1.x.

**Comment by 17patelumang** [comment]
@karllessard  yes adding that would be helpful since i an run TF 1.15.x savedmodel in TF 2.x without any issue

**Comment by karllessard** [comment]
@17patelumang , like @saudet said previously, if you are using `_wordpiece_tokenizer.dylib` that came from Python packages for TF1.x, then you need to run your Java app with TF1.15 and not the new artifacts distributed by this package, which are based to TF2.x

If you want to run the model on TF2.x, then you need to use `_wordpiece_tokenizer.dylib` coming out TF2.x Python packages, as indicated by @Craigacp . But again, it will still not work if on our side we don't add `libtensorflow_framework.2.dylib` to our distribution, that's a task to be done on our side first.

**Comment by 17patelumang** [comment]
@karllessard thanks , do i open feature request for adding `libtensorflow_framework.2.dylib` in the distribtuion ? also i think we need to add for different platforms correct ? since `.dylib` is platform specific .

**Comment by karllessard** [comment]
Yes it will be platform specific, just keep this issue opened, that will do, thanks!

**Comment by saudet** [comment]
@karllessard Right, we just need to remove `--config=monolithic` from the build line to get at that file, but your java_op_gen_tool won't work without that, so you'll need to figure out something for that first.

**Comment by karllessard** [comment]
> @karllessard Right, we just need to remove `--config=monolithic` from the build line to get at that file, but your java_op_gen_tool won't work without that, so you'll need to figure out something for that first.

Oh, I just read that after drafting [this PR](https://github.com/tensorflow/java/pull/44), I'll give it a try, I guess it will preserve the original size of our artifact.

**Comment by ericxsun** [comment]
actually, the [main-tensorflow-repo](https://github.com/tensorflow/tensorflow/blob/d9788a058ffe36ebf71fd1a4651d5849ab882538/tensorflow/java/BUILD) has changed to load version from `resources/tensorflow-version-info`, see         `NativeLibrary.class.getClassLoader().getResourceAsStream("tensorflow-version-info")` (https://github.com/tensorflow/tensorflow/blob/d9788a058ffe36ebf71fd1a4651d5849ab882538/tensorflow/java/src/main/java/org/tensorflow/NativeLibrary.java#L174);

**Comment by karllessard** [comment]
(closed by mistake)

**Comment by karllessard** [comment]
> actually, the main-tensorflow-repo has changed to load version from resources/tensorflow-version-info, see NativeLibrary.class.getClassLoader().getResourceAsStream("tensorflow-version-info"

Thanks @ericxsun , can you please give it a try and/or make a PR for this?

**Comment by karllessard** [comment]
Ok, so PR #44 was merged, which came with an upgrade to TF2.2 but also with changes that support back loading of custom ops libraries, like in TF1.x. @17patelumang , once the new artifacts [are done being deployed](https://github.com/tensorflow/java/actions/runs/107733330), can you please give it another try?

BTW, I've tried loading the `tensorflow-text` custom op library like in your example and ended up with this error: `undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs`, which seems to be a common issue with this library on TF > 2.0, check [this thread](https://github.com/tensorflow/text/issues/192) for more details. But at least the initial issue (looking for `libtensorflow_framework.so.2`) is now resolved.

Also, note that custom ops libraries probably don't work on Windows since TF is still built as a monolithic binary on this platform, as [configured by TensorFlow](https://github.com/tensorflow/tensorflow/blob/c4a9de96742d85a8772e3868fc2f13955a195e18/.bazelrc#L282). There is also an [interesting thread](https://github.com/tensorflow/custom-op/issues/24) on this topic and it looks like they came up with a [pythonic solution](https://github.com/tensorflow/custom-op/blob/23f042faa10590b49541f9961c2bf6b4052c83d7/configure.sh#L155) to fix it... We need to do more research to understand what should done to enable it in Java.

**Comment by 17patelumang** [comment]
@karllessard sure please let me know when to try.

**Comment by karllessard** [comment]
> @karllessard sure please let me know when to try.

You can do it now

**Comment by 17patelumang** [comment]
@karllessard please give me 2 days  i will respond by friday.

**Comment by 17patelumang** [comment]
@karllessard not working , now its complains of adding to class path

**Comment by karllessard** [comment]
@17patelumang can you please provide the full trace of that last issue?

**Comment by 17patelumang** [comment]
its the same code as above , but not at the first line of package it shows "The type org.tensorflow.tools.ndarray.FloatNdArray cannot be resolved. It is indirectly referenced from required .class 
 files"

**Comment by karllessard** [comment]
@17patelumang are you running your code snippet in IntelliJ? There is a [known issue](https://github.com/tensorflow/java-models/issues/4) where it cannot resolve properly the transitive dependencies of `tensorflow-core-platform`, it seems that you have hit that bug.

If so, can you please retry to run your test outside of it (maybe my using the `java -jar` command line) or try this [simple configuration tweak](https://github.com/tensorflow/java-models/issues/4#issuecomment-631629603) I’ve been using as a workaround?

**Comment by karllessard** [comment]
@saudet , as we discussed during the meeting, see [the last paragraph of this comment](https://github.com/tensorflow/java/issues/43#issuecomment-629924586) for more details concerning the lack of support for custom ops on Windows.

BTW @17patelumang , did you had any chance to retry it again with the last tips I gave you?

**Comment by karllessard** [comment]
I'm closing this issue now, on my side custom ops can be loaded without problem on Linux and MacOS. We will open another issue for Windows if that is requested.
