### ISSUE TITLE
Combined Div and Reshape is not fetching the correctly shaped Tensor in 0.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by pyrator** [tensorflow/java#430]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Windows 11 x86\_64
- TensorFlow installed from : binary
- TensorFlow version : 0.5.0-SNAPSHOT
- Java version: 14.0.2
- Java command line flags (e.g., GC parameters):
- CUDA/cuDNN version: 11.2 / 8100
- GPU model and memory: NVIDIA GeForce RTX 2070 SUPER with 5978 MB memory

**Describe the current behavior**
With Tensorflow release version 0.5.0-SNAPSHOT the output for the Tensor shape is [529, 782, 3]
**Describe the expected behavior**
With Tensorflow release version 0.4.0 the resulting Tensor shape is [1, 529, 782, 3]
**Code to reproduce the issue**

`
    import org.tensorflow.Graph;
    import org.tensorflow.Session;
    import org.tensorflow.op.Ops;
    import org.tensorflow.op.core.Constant;
    import org.tensorflow.op.core.Reshape;
    import org.tensorflow.op.image.DecodeJpeg;
    import org.tensorflow.op.io.ReadFile;
    import org.tensorflow.types.TFloat32;
    import org.tensorflow.types.TString;
    import org.tensorflow.types.TUint8;
    
    
    public class TestReadDivReshapeImageV1 {
    
        public static void main(String[] params) {
            try (Graph g = new Graph(); Session s = new Session(g)) {
                Ops tf = Ops.create(g);
                //my test image
                String imagePath = "testimages/dog.jpg";
                Constant<TString> fileName = tf.constant(imagePath);
                ReadFile readFile = tf.io.readFile(fileName);
                Session.Runner runner = s.runner();
                DecodeJpeg.Options options = DecodeJpeg.channels(3L);
                DecodeJpeg decodeImage = tf.image.decodeJpeg(readFile.contents(), options);
                //fetch image from file
                TUint8 inputImage = (TUint8) runner.fetch(decodeImage).run().get(0);
                Reshape<TFloat32> reshapeDivInput = tf.reshape(tf.math.div(
                                tf.dtypes.cast(tf.constant(inputImage), TFloat32.class),
                                tf.constant(255.0f)
                        ),
                        tf.array(1,
                                inputImage.shape().asArray()[0],
                                inputImage.shape().asArray()[1],
                                inputImage.shape().asArray()[2]
                        )
                );
                try (TFloat32 resizeInputTensor = (TFloat32) s.runner().fetch(reshapeDivInput).run().get(0)) {
                    System.out.println(resizeInputTensor.shape().toString());
                }
            }
        }
    }
`
Splitting the Div and Reshape operations provides the correct shaped tensor
i.e.

`
    import org.tensorflow.Graph;
    import org.tensorflow.Session;
    import org.tensorflow.op.Ops;
    import org.tensorflow.op.core.Constant;
    import org.tensorflow.op.core.Reshape;
    import org.tensorflow.op.image.DecodeJpeg;
    import org.tensorflow.op.io.ReadFile;
    import org.tensorflow.op.math.Div;
    import org.tensorflow.types.TFloat32;
    import org.tensorflow.types.TString;
    import org.tensorflow.types.TUint8;

    public class TestReadDivReshapeImageV2 {
        public static void main(String[] params) {
            try (Graph g = new Graph(); Session s = new Session(g)) {
                Ops tf = Ops.create(g);
                //my test image
                String imagePath = "testimages/dog.jpg";
                Constant<TString> fileName = tf.constant(imagePath);
                ReadFile readFile = tf.io.readFile(fileName);
                Session.Runner runner = s.runner();
                DecodeJpeg.Options options = DecodeJpeg.channels(3L);
                DecodeJpeg decodeImage = tf.image.decodeJpeg(readFile.contents(), options);
                //fetch image from file
                TUint8 inputImage = (TUint8) runner.fetch(decodeImage).run().get(0);
                Div<TFloat32> div = tf.math.div(
                        tf.dtypes.cast(tf.constant(inputImage), TFloat32.class),
                        tf.constant(255.0f)
                );
                try (TFloat32 divTensor = (TFloat32) s.runner().fetch(div).run().get(0)) {
                    Reshape<TFloat32> reshapeDivInput = tf.reshape(tf.constant(divTensor),
                            tf.array(1,
                                    inputImage.shape().asArray()[0],
                                    inputImage.shape().asArray()[1],
                                    inputImage.shape().asArray()[2]
                            )
                    );
                    try (TFloat32 resizeInputTensor = (TFloat32) s.runner().fetch(reshapeDivInput).run().get(0)) {
                        System.out.println(resizeInputTensor.shape().toString());
                    }
                }
            }
        }
    }
`

**Comment by karllessard** [comment]
Hi @pyrator , I've just tried your first snippet on 0.5.0-SNAPSHOT and it does give me the expanded shape ([1, 1600, 2560, 3] in my case). We've just upgraded to TF2.8, maybe something was fixed, the updated artifacts are actually being built so you can probably try it again tomorrow and see if the problem still remain on your side.

Meanwhile, there is a simpler way to achieve what you are doing here, where you can easily read and expand the shape of your image in a single session run, by using the operation [`expandDims`](https://github.com/tensorflow/java/blob/be7361235b4ff651842c8411a6b027db951aea25/tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java#L2502). Can you give this a try and see how it behaves on your side? Here's the updated code, which gives me the same result:

```java
  public static void main(String[] params) {
    String imagePath = "images/inferno1.jpg";

    try (Graph g = new Graph(); Session s = new Session(g)) {
      Ops tf = Ops.create(g);
      ReadFile readFile = tf.io.readFile(tf.constant(imagePath));
      DecodeJpeg decodedImage = tf.image.decodeJpeg(readFile.contents(), DecodeJpeg.channels(3L));
      Div<TFloat32> normalizedImage = tf.math.div(tf.dtypes.cast(decodedImage, TFloat32.class), tf.constant(255.0f));
      ExpandDims<TFloat32> reshapedImage = tf.expandDims(normalizedImage, tf.constant(0));
      try (TFloat32 output = (TFloat32) s.runner().fetch(reshapedImage).run().get(0)) {
        System.out.println(output.shape().toString());
      }
    }
  }
```

**Comment by pyrator** [comment]
Thankyou, the ExpandDims does exactly as I want with normalizing and reshaping images into tensors. I can check out the 0.5.0-SNAPSHOT again tomorrow to see if the combined Div and Reshape ops also work as there may be a case when something else is required.
Also conversely from reading the docs, a tf.squeeze on axis 0 returns the original tensor shape.

**Comment by pyrator** [comment]
I've just cleaned and retried with latest  0.5.0-SNAPSHOT jars and everything is working with combined Div and Reshape ops too, so I will close this.
