### ISSUE TITLE
how to implement image preprocessing ？

### ISSUE THREAD

**Issue by zouxiaodong** [tensorflow/java#442]
hi, 
  how to implement the follow code snippet  with java？

def tf_preprocess(filename):
    img_str = tf.compat.v1.read_file(filename)
    img_decode = tf.io.decode_jpeg(img_str, channels=3, dct_method='INTEGER_ACCURATE')
    img_converted = tf.cast(img_decode, tf.float32)
    img_scaled = tf.compat.v1.image.resize_images(img_converted, (224,224), method=0)
    img = tf.reshape(img_scaled, (224,224,3))
    img = tf.divide(tf.subtract(img, 225/2), 128)
    img = tf.expand_dims(img, 0)
    return img

**Comment by zouxiaodong** [comment]
duplicated #236

**Comment by karllessard** [comment]
Hi @zouxiaodong , if you look at the example we have in `java-models`, be careful because this one does not use `tf.expandDims` to add the batch dimension of 1 but you should, all these ops are also available in Java. (I need to find some time to update it...)
