### ISSUE TITLE
no jnitensorflow in java.library.path during Maven installation

### ISSUE THREAD

**Issue by kensens** [tensorflow/java#445]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04 x86\_64): Linux Debian x86_64
- TensorFlow installed from (source or binary): trying to install
- TensorFlow version: I'm ok with any version, but the installation instructions are for 0.3.3
- Java version (i.e., the output of `java -version`): openjdk version "11.0.13" 2022-04-05
- Java command line flags (e.g., GC parameters):
- Installed from Maven Central?: Trying to
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I get the following errors when following the Maven installation directions:

> Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]

> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project hellotensorflow: An exception occured while executing the Java class. **no jnitensorflow in java.library.path**: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]: /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libjnitensorflow.so: libstdc++.so.6: cannot open shared object file: No such file or directory -> [Help 1]

Someone else on GitHub has recently come across the exact same issue, but using Gradle: https://stackoverflow.com/questions/71791929/java-lang-unsatisfiedlinkerror-no-jnitensorflow-in-java-library-path-tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the instructions here [https://www.tensorflow.org/jvm/install#example_program](https://www.google.com/url?sa=D&q=https%3A%2F%2Fwww.tensorflow.org%2Fjvm%2Finstall%23example_program), creating `pom.xml` and `src/main/java/HelloTensorFlow.java` exactly as described, then running `mvn -q compile exec:java`.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project hellotensorflow: An exception occured while executing the Java class. no jnitensorflow in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]: /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libjnitensorflow.so: libstdc++.so.6: cannot open shared object file: No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by saudet** [comment]
> libstdc++.so.6: cannot open shared object file: No such file or directory

You'll need to install libstdc++. That's required by both OpenJDK and TensorFlow.

**Comment by kensens** [comment]
Thanks for the comment. I already have libstdc++ installed, and it exists in a subdirectory of `/usr/lib/`:

```
$ sudo apt-get install libstdc++6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libstdc++6 is already the newest version (11.2.0-16).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo find /usr/lib/ -name libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
```

The purpose of creating this issue is twofold: I would like help actually getting TensorFlow Java installed correctly, and it would also be great if the TensorFlow Java documentation could be updated with installation instructions that "just work".

**Comment by saudet** [comment]
It does "just work" on typical installations of Linux. It looks like you have a special installation that doesn't let users link custom libraries against /usr/lib/libstdc++.so.6. I'm afraid you'll need to figure out how to make that work on your unusual setup.

**Comment by Craigacp** [comment]
What does the output of ldd look like for `/usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libjnitensorflow.so`? (Also you didn't redact that path in all parts of your issue). Is the Google version of Debian locked down in some way wrt library linking?

**Comment by kensens** [comment]
```
$ ldd /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libjnitensorflow.so
        linux-vdso.so.1 (0x00007ffde5f34000)
        libtensorflow_cc.so.2 => /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libtensorflow_cc.so.2 (0x00007fbc1fa3a000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbc1f818000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbc1f6d5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbc1f6bb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbc1f69a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbc1f4be000)
        libtensorflow_framework.so.2 => /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libtensorflow_framework.so.2 (0x00007fbc1d8fa000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbc1d8f3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbc1d8e8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbc2aa85000)
```
> Is the Google version of Debian locked down in some way wrt library linking?

Great question, I don't know.

But, I have repeated the installation instructions on a standard Linux VM and it worked successfully. Although slightly inconvenient, using that VM will be fine for my purposes. So, really the issue was that my machine was unusual :)

Thanks to both of you for helping out.

**Comment by Craigacp** [comment]
If you're ok with running a few more experiments I'd like to see if there is something we can document about it. If TF-Java doesn't work on Google's laptops then that's a problem.

Could you try running `System.load(<absolute-path-to-libtensorflow_framework.so>)` twice? Once to the path in your home directory, and once to the same files but copied somewhere else (e.g. `/tmp`)? I'm wondering if it is setup to prevent you from loading so files from the home directory which probably shouldn't contain them.

**Comment by kensens** [comment]
I get the same issue in both `libtensorflow_framework.so.2` cases and for `libstdc++.so.6` on my original Google machine:
```
$ cat Load.java
public class Load {
  public static void main(String[] args) {
    System.load(args[0]);
  }
}

$ java Load.java /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libtensorflow_framework.so.2
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libtensorflow_framework.so.2: libstdc++.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2444)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2500)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2716)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2629)
        at java.base/java.lang.Runtime.load0(Runtime.java:769)
        at java.base/java.lang.System.load(System.java:1840)
        at Load.main(Load.java:3)

$ java Load.java /tmp/libtensorflow_framework.so.2 
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libtensorflow_framework.so.2: libstdc++.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2444)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2500)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2716)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2629)
        at java.base/java.lang.Runtime.load0(Runtime.java:769)
        at java.base/java.lang.System.load(System.java:1840)
        at Load.main(Load.java:3)

$ java Load.java /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29: libgcc_s.so.1: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2444)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2500)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2716)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2629)
        at java.base/java.lang.Runtime.load0(Runtime.java:769)
        at java.base/java.lang.System.load(System.java:1840)
        at Load.main(Load.java:3)
```

Repeating this on the GCE VM where installation worked, I no longer get any such errors for `libtensorflow_framework.so.2` or `libstdc++.so.6`.

**Comment by Craigacp** [comment]
Well that's deeply weird. Maybe the Java install is quarantined in some sense so it can't trigger arbitrary dlopens properly? I'm not sure how the JVM would even start up in that case. It's clearly able to read the files a little bit otherwise it wouldn't know that libstdc++ needed libgcc_s, but I don't have any explanation for why it can't do dependent loads.

**Comment by karllessard** [comment]
And if you set `LD_LIBRARY_PATH` explicitly to where libstdc++ is, does it load at least this one? i.e.

`LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu java Load.java /usr/redacted/.javacpp/cache/tensorflow-core-api-0.3.3-linux-x86_64.jar/org/tensorflow/internal/c_api/linux-x86_64/libtensorflow_framework.so.2`

Does your `LD_LIBRARY_PATH` env variable already set to something?
