### ISSUE TITLE
Operator with more than 8 outputs

### ISSUE THREAD

**Issue by roywei** [tensorflow/java#45]
Hi, it seems the java api can't create an output more than 8. This is a big limitation especially on split operators. 
Here is a reproducible code, I'm using `tensorflow-core-api` latest SNAPSHOT version.
```
package ai.djl.tensorflow.engine;

import org.tensorflow.EagerSession;
import org.tensorflow.op.Ops;
import org.tensorflow.types.TInt64;

public class Tftest {
    public static void main(String[] args) {
        EagerSession eagerSession = EagerSession.options().async(true).build();
        Ops tf = Ops.create(eagerSession);
        // creates a (20, 20) tensor with zeros and split to 10 tensors equally on axis 0,
        // should return 10 tensors each with shape(2, 20).
        tf.splitV(
                tf.zeros(tf.constant(new long[]{20,20}), TInt64.DTYPE),
                tf.constant(10),
                tf.constant(0),
                10L
        );
    }
}
```

error message:
```
Exception in thread "main" java.lang.IllegalArgumentException: Expecting 10 outputs, but *num_retvals is 8
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:72)
	at org.tensorflow.EagerOperationBuilder.execute(EagerOperationBuilder.java:302)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:68)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:57)
	at org.tensorflow.op.core.SplitV.create(SplitV.java:64)
	at org.tensorflow.op.Ops.splitV(Ops.java:5715)
	at ai.djl.tensorflow.engine.Tftest.main(Tftest.java:11)
```

**Comment by roywei** [comment]
The only possible cause may be [here](https://github.com/tensorflow/tensorflow/pull/28212/files#diff-d48204d45bb1a0c42ec898235026aa44R92), but this code is in the main TF repo, not in this repo.  I think API in this repo switched to JavaCPP instead of JNI, so it should not be affected? 

Currently I can workaround this by doing split multiple times each time with a maximum of 8 outputs. But it will affect performance as this operator will be used heavily when processing datasets.

Please help take a look, thank you so much!

cc @karllessard @saudet

**Comment by saudet** [comment]
That limit is still there: https://github.com/tensorflow/java/blob/master/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerOperationBuilder.java#L229

**Comment by roywei** [comment]
Thanks @saudet ! Do you have any suggestion on a good number to fix? It mainly affects operators that returns iterables.  
Use case I can think of: 
1) split the data to multiple devices. 
2) split a batch of data and do some padding/processing for each row.
