### ISSUE TITLE
looking for facility to disable learning phase as we do in python tf.keras.backend.learning_phase(0)

### ISSUE THREAD

**Issue by sudha1988** [tensorflow/java#465]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
we can load a model as below
```
 modelFiles: List[String] = List(
      "saved_model.pb",
      "keras_metadata.pb",
      "variables/variables.data-00000-of-00001",
      "variables/variables.index"
    )
     modelDir = "/Models/lstm_model_fullname_with_watchlist"
     tempDirectory = Files.createTempDirectory("lstm").toFile
  savedModel = SavedModelBundle.load(tempDirectory.getAbsolutePath, "serve")
    new LSTMModel(
      session = savedModel.session()
    )
```
and call the predict operation as 
```
 val input1: Tensor[_] = Tensor.create(embed(name1))
    val input2: Tensor[_] = Tensor.create(embed(name2))
    val result: Tensor[_] = session.runner()
      .fetch("StatefulPartitionedCall:0")
      .feed("serving_default_input_1:0", input1)
      .feed("serving_default_input_2:0", input2)
      .run().get(0)
```
We need to get an option to disable learning _phase

**Will this change the current api? How?**

 functionality wise the model will stop learning but give the prediction results. 

**Who will benefit with this feature?**
In my case model is in mature state, I dont want my model to learn, so it will cutdown its respective latency.  

**Any Other info.**
I read this and assumed kera package not available hence tf.keras.backend.learning_phase its corresponding java code might not be available
https://github.com/tensorflow/java/issues/217

**Comment by Craigacp** [comment]
This is controlled by how you export the SavedModel from python. If the function doesn't do backpropagation then TF-Java won't do it either.

**Comment by sudha1988** [comment]
@Craigacp could you kindly give some more elaboration ? what do you mean by ' how you export the SavedModel'?  do you mean its controlled by model?If there is a reference kindly share...?

**Comment by Craigacp** [comment]
TensorFlow-Java will execute the function you specify from the saved model. If that function involves backpropagation then it will update the model, and if it's just inference then it will not. It depends on how the function is specified in the model that was exported which isn't under our control.

**Comment by sudha1988** [comment]
Thanks for explaining @Craigacp
