### ISSUE TITLE
Make Graph accessible from Session

### ISSUE THREAD

**Issue by arianmaghsoudnia** [tensorflow/java#479]
**System information**
- TensorFlow version : 0.4.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I would like to have access to the [Graph attribute](https://github.com/tensorflow/java/blob/851fcf6b205a5ad5028b6f8afa4b2fe16a1cb0f9/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Session.java#L706) of the Session. Is there a reason it is private?

**Will this change the current api? How?**
Yes. Makes an existing attribute public.

**Who will benefit with this feature?**
If you have a loaded session and need to access the detail of your graph.

**Comment by karllessard** [comment]
I guess it is safe to expose it, yes, I don't see why not. Would you be interested to push a PR for this?

**Comment by AyushABD-17** [comment]
code base is in java?

**Comment by manojava98** [comment]
Hi, @karllessard I can raise PR for this one, kindly let me know if this is okay with you. Thanks in advance!

**Comment by karllessard** [comment]
Yes @manojava98 , please do!

**Comment by manojava98** [comment]
Hi @karllessard I have raised the PR #535  . Kindly, check

**Comment by Craigacp** [comment]
Fixed in `master`.
