### ISSUE TITLE
How to deal with the cold start problem？

### ISSUE THREAD

**Issue by wenyangchou** [tensorflow/java#489]
**Describe the current behavior**
First  prediction after loading the model, it cost a long time. 

**Describe the expected behavior**
It can performance well Whether it is the first prediction or not.

**Comment by saudet** [comment]
That's typically what Graal Native Image is for...

**Comment by wenyangchou** [comment]
> That's typically what GraalVM Native Image is for...
I don't quite understand why this has something to do with `GraalVM Native Image `. 
My scenario is to load a TF model with java to provide RPC services, a kind of RPC protocol that tf-serving is not supported.
In tf-serving, we can add warm-up file in the model. So how do I implement it in java, or is there any switch to let warm up the tf model?

**Comment by Craigacp** [comment]
There's no switch to let TF-Java warm up the model, you'll have to do that in your code by iterating some set of example computations.

**Comment by wenyangchou** [comment]
What a pity, thanks

**Comment by saudet** [comment]
FYI, there's also TF Lite, which is for low latency applications like that.
