### ISSUE TITLE
Operand problem

### ISSUE THREAD

**Issue by FriedaSmith** [tensorflow/java#49]
The method conv2d(Operand<T>, Operand<T>, List<Long>, String, Conv2d.Options...) in the type NnOps is not applicable for the arguments (Constant<TFloat32>, Tensor<TFloat32>, List<Long>).
But how can I generate the Operand<T> type?

**Comment by karllessard** [comment]
A `Constant` is an `Operand`, so in your example you probably just need to convert the second argument of type `Tensor` to a `Constant` as well, by using [this operator](https://github.com/tensorflow/java/blob/a9d3b1783b847ca8138dda0880f3a447347ef95c/tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java#L1691) for example

**Comment by FriedaSmith** [comment]
> A Constant is an Operand, so in your example you probably just need to convert the second argument of type Tensor to a Constant as well, by using this operator for example

Thanks. But Your link did not find a solution. Some of my questions have been filtered, the text is as follows：
The method conv2d(Operand< T >, Operand< T >, List< Long >, String, Conv2d.Options...) in the type NnOps is not applicable for the arguments (Constant< TFloat32 >, Tensor< TFloat32 >, List< Long >).

**Comment by Craigacp** [comment]
You need to supply the padding type. See https://github.com/tensorflow/java-models/blob/master/tensorflow-examples/src/main/java/org/tensorflow/model/examples/mnist/CnnMnist.java line 102.

**Comment by FriedaSmith** [comment]
> You need to supply the padding type. See https://github.com/tensorflow/java-models/blob/master/tensorflow-examples/src/main/java/org/tensorflow/model/examples/mnist/CnnMnist.java line 102.

Thank you. It is very useful.
