### ISSUE TITLE
Tensor type issue

### ISSUE THREAD

**Issue by SaherAlSous** [tensorflow/java#505]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Tensorflow for Java (using Korlin)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04 x86\_64): I have Ubuntu 20.
- TensorFlow installed from (source or binary): implementation("org.tensorflow:tensorflow-core-platform:0.5.0")
- TensorFlow version (use command below): TF 2
- Java version (i.e., the output of `java -version`): 8
- Java command line flags (e.g., GC parameters): 
- Python version (if transferring a model trained in Python): 3.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I'm trying to find a way to use tensorflowmodel in Spring Boot, I loaded the model successfully, and created the needed tensor, but I can't make a call to get the result from the model because of this error:
Caused by: org.tensorflow.exceptions.TFInvalidArgumentException: Expects arg[0] to be float but uint8 is provided
I checked the model signature and it was like this:
Signature for "serving_default":

`
Method: "tensorflow/serving/predict"
    Inputs:
        "input_1": dtype=DT_FLOAT, shape=(-1, 299, 299, 3)
    Outputs:
        "dense_3": dtype=DT_FLOAT, shape=(-1, 41)

Signature for "__saved_model_init_op":
    Outputs:
        "__saved_model_init_op": dtype=DT_INVALID, shape=()
`

my tensor details are DT_UINT8 tensor with shape [299, 299, 3].
When I changed my tensor data type into float like this:
`val imageShape = TFloat32.tensorOf(runner.fetch(decodeImage).run()[0].shape())
val reshape = tf.reshape(
            decodeImage,
            tf.array(
                -1.0f,
                imageShape[0].getFloat(),
                imageShape[1].getFloat(),
                imageShape[2].getFloat())
            )`
I got this error:
org.tensorflow.exceptions.TFInvalidArgumentException: Value for attr 'Tshape' of float is not in the list of allowed values: int32, int64

**Describe the expected behavior**
Doing inference / expectation succesffuly.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Loading the model in TFServices:
`
fun model(): SavedModelBundle  {
        return SavedModelBundle
            .loader("/home/***/src/main/resources/pd/")
            .withRunOptions(RunOptions.getDefaultInstance())
            .load()
    }`
Building the Tensor and calling the model
```kotlin
        val graph = Graph()
        val session = Session(graph)
        val tf = Ops.create(graph)
        val fileName = tf.constant("/home/***/src/main/resources/keyframe_1294.jpg")
        val readFile = tf.io.readFile(fileName)
        val runner = session.runner()
        val decodingOptions = DecodeJpeg.channels(3)
        val decodeImage = tf.image.decodeJpeg(readFile.contents(), decodingOptions)
        val imageShape = runner.fetch(decodeImage).run()[0].shape()
        val reshape = tf.reshape(
            decodeImage,
            tf.array(
                -1,
                imageShape.asArray()[0],
                imageShape.asArray()[1],
                imageShape.asArray()[2])
            )
        val tensor = runner.fetch(reshape).run()[0]
        val inputMap = mutableMapOf("input_tensor" to tensor)
        println(tensor.shape())
        println(tensor.dataType())
        println(tensor.asRawTensor())
        val result = tfService.model().function("serving_default").call(inputMap)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Craigacp** [comment]
The reshape command you're using isn't a cast, you'll need to cast it from uint8 to float32 assuming that's what the model wants.

**Comment by karllessard** [comment]
+1 to @Craigacp comment, use `tf.dtypes.cast` to convert your Uint8 decoded image to Float.

Also it looks like you are trying to run TF eagerly but using a graph Session? You might want to look at EagerSession instead, especially that the way you are currently doing will leak, as you need close the output tensors (nor the inputs).

**Comment by SaherAlSous** [comment]
Dear @Craigacp @karllessard 
thank you for the clarification, the types were accepted indeed, 
the type of the tensor now is 
> DT_FLOAT tensor with shape [299, 299, 3]

except that the reshape of the first value of the reshaped array didn't work as expected and i'm getting this error
>org.tensorflow.exceptions.TFInvalidArgumentException: input must be 4-dimensional[299,299,3]

I did this way
```
val castedImage = tf.dtypes.cast(decodeImage, TFloat32::class.java)
val imageShape = runner.fetch(castedImage).run()[0].shape()
val reshape = tf.reshape(
  decodeImage,
      tf.array(
            1,
            imageShape.asArray()[0],
            imageShape.asArray()[1],
            imageShape.asArray()[2])
    )
```

i still don't know how to do it with eager session, excuse me for that!
