### ISSUE TITLE
how to use importGraphDef to load model.pb file?

### ISSUE THREAD

**Issue by MrbigBox** [tensorflow/java#508]
I want to load a exist model to use.
I referred to the following URL:
https://github.com/tensorflow/java-models/blob/master/tensorflow-examples-legacy/label_image/src/main/java/LabelImage.java

I use this in my project , and get error in importGraphDef
The error is 
"The method importGraphDef(GraphDef) in the type Graph is not applicable for the arguments (byte[])"

I looked at the definition of importGraphDef in the Graph.class.
"/**
   * Import a representation of a TensorFlow graph.
   *
   * <p>The representation of the graph, referred to as a {@code GraphDef}, can be generated by
   * {@link #toGraphDef()} and equivalents in other language APIs.
   *
   * @param graphDef {@code GraphDef} proto to import
   * @throws IllegalArgumentException if graphDef is not a recognized serialization of a graph.
   * @see #importGraphDef(GraphDef, String)
   */
  public void importGraphDef(GraphDef graphDef) throws IllegalArgumentException {
    importGraphDef(graphDef, "");
  }"

It seems that the new importGraphDef now requires data of type GraphDef instead of byte[].
How can I use new importGraphDef to load a model.pb file?

**Comment by Craigacp** [comment]
`GraphDef` is a protobuf, so you can construct one from a `byte[]` with `GraphDef.parseFrom(byte[])`.

**Comment by MrbigBox** [comment]
Okay, I understand. Thank you.
