### ISSUE TITLE
Distributing an Apple Silicon binary

### ISSUE THREAD

**Issue by npfp** [tensorflow/java#515]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Tensorflow Java 0.5
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Now that Apple silicon M1 instances are available as Github runners, it would be really interesting for all Apple Silicon M1 users to distribute binary for this platform.

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
All Apple M1 users.

**Any Other info.**

**Comment by Craigacp** [comment]
We're working on it - https://github.com/tensorflow/java/issues/394#issuecomment-1847887092

**Comment by Craigacp** [comment]
TF-Java 1.0.0-rc1 has Apple Silicon binaries - https://github.com/tensorflow/java/releases/tag/v1.0.0-rc.1
