### ISSUE TITLE
Tensors.create factory method is not supported

### ISSUE THREAD

**Issue by vissood** [tensorflow/java#53]
Java API does not support factory method for creating Tensor
Tensors.create()  - https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Tensors

**Comment by Craigacp** [comment]
Those methods are horribly inefficient due to the way Java multidimensional arrays are constructed, so they've been removed from the new API.

**Comment by vissood** [comment]
Thanks for reply!! 
Can you please share what is alternative way?

**Comment by hegdeashwin** [comment]
I'm too looking for some better alternative, any help would be great.

**Comment by Craigacp** [comment]
It depends what you are trying to do, but the Tensor infrastructure now creates tensors from NdArrays which are defined in tensorflow-tools. To use the old slow path you can create an NdArray using `org.tensorflow.tools.ndarray.StdArrays`, and then feed the resulting object into `<Type>.tensorOf()`, where <type> is the type of `Tensor` you want to create (e.g. `TFloat32`, `TInt32` etc). If your data isn't stored in a java multidimensional array then we recommend that you write it directly into an `NdArray` after allocating one of the appropriate size (using `org.tensorflow.types.<type>.tensorOf(shape)`.

**Comment by karllessard** [comment]
Just jumping into this ticket as well, so the proper way to create tensors now is by using factories exposed by the type themselves. Here's a few examples for [32-bit integer tensors](https://github.com/tensorflow/java/blob/ea00c79506c53b2623cd49f2c090f98a981e6659/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/types/TInt32.java#L36):

```java
Tensor<TInt32> scalar = TInt32.scalarOf(0);

Tensor<TInt32> array = TInt32.vectorOf(1, 2, 3, 4);

// this is efficient for large tensors, as it does not require to preallocate or 
// duplicate the whole data before feeding the tensor
Tensor<TInt32> matrix = TInt32.tensorOf(Shape.of(2, 4), data -> 

    // your input loop here, you could read from an `InputStream`, etc. but let's use
    // a simple case as an example
    data.set(NdArrays.vectorOf(1, 2, 3, 4), 0)
        .set(NdArrays.vectorOf(5, 6, 7, 8), 1)
); 

// this can be more convenient for small tensors, for the improved syntax
Tensor<TInt32> matrix3d = TInt32.tensorOf(StdArrays.ndCopyOf(new int[][][] {
  {
     {1, 2, 3}, {4, 5, 6}
  },
  {
     {7, 8, 9}, {10, 11, 12}
  }  
}));

// and more options...
```
You can do pretty much the same using the [`Constant`](https://github.com/tensorflow/java/blob/master/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/op/core/Constant.java) for tensors with a fix value in a graph.

And finally, you can rely on the [`Tensor` factories](https://github.com/tensorflow/java/blob/ea00c79506c53b2623cd49f2c090f98a981e6659/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Tensor.java#L70) if you need better fine-tuning or selection of the datatype at runtime.
