### ISSUE TITLE
right dependency for org.tensorflow.proto.framework?

### ISSUE THREAD

**Issue by ngbusca** [tensorflow/java#537]
**System information**
- OS Platform and Distribution:  Linux Ubuntu 16.04 x86\_64
- TensorFlow installed from (source or binary): maven
- TensorFlow version: 1.0.0
- Java version (i.e., the output of `java -version`): 11
- Java command line flags (e.g., GC parameters):
- Installed from Maven Central?: yes
- CUDA/cuDNN version: 12.3 / 8.9
- GPU model and memory: NVIDIA RTX 5000

**Describe the problem**

In the previous version of TF 0.5.0 I was able to configure GPU properties via ConfigProto:

```
       ConfigProto configproto = ConfigProto
                .newBuilder()
                .setAllowSoftPlacement(false)
                .setGpuOptions(GPUOptions.newBuilder()
                        .setForceGpuCompatible(true)
                        .setPerProcessGpuMemoryFraction(0.9)
                        .setAllowGrowth(true).build())
                .build();
```

In 1.0.0 maven doesn't find:

```
import org.tensorflow.proto.framework.ConfigProto;
import org.tensorflow.proto.framework.GPUOptions;
import org.tensorflow.proto.framework.GraphDef;
```

What are the right dependencies to include for 1.0.0 ?
I have the following dependencies:
```
  <dependency>
      <groupId> org.tensorflow </groupId>
      <artifactId> tensorflow-core-native </artifactId>
      <version> 1.0.0-rc.1 </version>
      <classifier>linux-x86_64-gpu</classifier>
  </dependency>

  <dependency>
      <groupId> org.tensorflow </groupId>
      <artifactId> tensorflow-core-api </artifactId>
      <version> 1.0.0-rc.1 </version>
  </dependency>
```
Thanks in advance

**Comment by Craigacp** [comment]
It's in tensorflow-core-native - https://github.com/tensorflow/java/blob/r1.0/tensorflow-core/tensorflow-core-native/src/gen/java/org/tensorflow/proto/ConfigProto.java.

A bunch of protos moved as part of the build changes.

**Comment by ngbusca** [comment]
But I have tensorflow-core-native in my pom...

**Comment by ngbusca** [comment]
Sorry, now I understand your comment :-) 

I replaced the import to:

```
import org.tensorflow.proto.ConfigProto;
import org.tensorflow.proto.GPUOptions;
import org.tensorflow.proto.GraphDef;
```
now it works!
