### ISSUE TITLE
Support for Java Libraries in Loading Keras 3.0 and .keras Models

### ISSUE THREAD

**Issue by kmizuki** [tensorflow/java#549]
Hello,
I failed to load a model trained using Python and Keras 3.0. Are Java models not supported for Keras 3.0 or loading .keras models? If not, are these features included in the future roadmap?

**Comment by Craigacp** [comment]
We can only load TF SavedModel. Loading Keras models will require a substantial effort to build the Keras layer in Java and then to parse their file format. I'm unsure if the Keras 3 file format is specified well enough to load in other places.
