### ISSUE TITLE
CUDA / cuDNN compatiblity matrix

### ISSUE THREAD

**Issue by DavidHuebner** [tensorflow/java#561]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 2.16.1 
- Java TensorFlow version: 1.0.0-rc.1
- Doc Link: https://github.com/tensorflow/java/blob/master/README.md

**Describe the documentation issue**
I cannot find information in the Java TensorFlow project regarding the required CUDA and cuDNN versions. I am aware of the [compatibility table](https://www.tensorflow.org/install/source#gpu) for the Python installation. I wonder if the same versions apply to these Java packages, specifically if version `1.0.0-rc.1`, which is based on `2.16.1`, requires CUDA `12.3` and cuDNN `8.9.7`? Any reference would be greatly appreciated. 

I am asking because this combination of CUDA/cuDNN versions seems to be rather difficult to install from the precompiled NVIDIA libraries, and I wonder if CUDA `12.2` and cuDNN `8.9.7` could also work.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** 
No

**Comment by karllessard** [comment]
Hi @DavidHuebner ,

We do not recompile ourselves the TF binaries anymore (since rc.1), therefore the Cuda compatibility is the same as with Python and C++.

**Comment by DavidHuebner** [comment]
Thank you for the quick response!
