### ISSUE TITLE
Maven coordinates not found

### ISSUE THREAD

**Issue by Ben-Epstein** [tensorflow/java#57]
**Describe the problem**
I'm sorry if this is a bad question, but I'm unable to find the maven coordinates for this project. You have a sample pom.xml but I can't find them on maven repo and when I try to add them I get errors that they can't be found. What am I missing?

**Comment by karllessard** [comment]
Are you looking for [this information](https://github.com/tensorflow/java#snapshots)?

**Comment by Ben-Epstein** [comment]
@karllessard  I understand now, thank you, I didn't realize you needed to add the Sonatype for mvn artifacts. It may be worth adding a note in the above section [Using Maven Artifacts ](https://github.com/tensorflow/java#using-maven-artifacts) that it's required.

**Comment by karllessard** [comment]
The section I've pointed you to is already under `Using Maven Artifacts`, as you suggested. Note that this extra-configuration is only required for the time being that the new generation of TF Java artifacts are only available as snapshots. After their first official release, it shouldn't be required anymore.
