### ISSUE TITLE
r0.5 - tensorflow-core-api compilation failing with a bunch of "src/gen/java/org/tensorflow/internal/c_api/Node.java: error: <identifier> expected" error

### ISSUE THREAD

**Issue by lvsubbu** [tensorflow/java#583]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Linux 
- IBM S390x Platform
- Tensorflow - 2.14.1
- TF Java - r0.5
- JavaCpp.jar 1.5.8 (build for IBM S390x platform)
- Java 11
- Tested JavaCpp.jar by sample application
- Tested Tensorflow 2.14.1 as well

**Describe the current behavior**
Successfully compiled and installed Javacpp package and Tensorflow 2.14.1 as well compiled. But when compiling tensorflow-core-api in java (r0.5), by mvn clean install -DskipTests -X, I am getting a bunch of "src/gen/java/org/tensorflow/internal/c_api/Node.java:[164,69] error: <identifier> expected"

It is not clear what the issue is coming. Is it due to a version mismatch or setting, the errors are not clear. But the line number of the code where it is failing is - src/gen/java/org/tensorflow/internal/c_api/Node.java
```
    164   public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
    165                           @StdString BytePointer type_attr_name, @Cast("bool") boolean update_full_type);
    166   public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
    167                           @StdString String type_attr_name, @Cast("bool") boolean update_full_type);
    168 
```

**Hints: A common observation is that @ByVal and @ByValue are present in those lines of code.**

> src/gen/java/org/tensorflow/internal/c_api/Node.java:[164,69] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[164,85] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[164,88] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[164,92] error: <identifier> expected

**Describe the expected behavior**
No error

**Code to reproduce the issue**
compile the tensorflow-core-api using "mvn clean install"

**Other info / logs**

> [165,26] error: illegal start of expression
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[165,36] error: ';' expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[165,64] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[165,65] error: illegal start of expression
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[165,78] error: ';' expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[165,103] error: ';' expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[166,69] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[166,85] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[166,88] error: <identifier> expected
> [ERROR] /tf_install/tensorflow/java/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java:[166,92] error: <identifier> expected

**Comment by Craigacp** [comment]
What java compiler are you using?

**Comment by lvsubbu** [comment]
Hi Adam Pocock, I am using openjdk-11
```
[root@1abed6702272 tensorflow]# java -version
openjdk version "11.0.25" 2024-10-15 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.25.0.9-1) (build 11.0.25+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.25.0.9-1) (build 11.0.25+9-LTS, mixed mode, sharing)
```

**Comment by lvsubbu** [comment]
Issue is in/for this 4 lines of code 

```
  public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
                          @StdString BytePointer type_attr_name, @Cast("bool") boolean update_full_type);
  public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
                          @StdString String type_attr_name, @Cast("bool") boolean update_full_type);
```

**Comment by lvsubbu** [comment]
Also, noticed this code is autogenerated is modified during the compilation 

+++ b/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/internal/c_api/Node.java
@@ -35,8 +35,6 @@ public class Node extends Pointer {
   // * def().attr() is authoritative.
   // TODO(irving): Replace with NodeInfo.
 
-  // TODO(mdan): This is only used by control_flow_deps_o_chains. Remove?
-
   // input and output types
   public native @Cast("tensorflow::int32") int num_inputs();
 
@@ -157,6 +155,17 @@ public class Node extends Pointer {
   // Erases type information from the node.
   public native void ClearTypeInfo();
 
+  // Update type information for a node with a list of inputs and/or outputs
+  // described by its TYPE_ATTR_NAME attr when removing some of these. The keys
+  // of INDEX_MAPPING are the indexes of the inputs/outputs that are not
+  // removed. dtype information in the TYPE_ATTR_NAME attr is always updated.
+  // Use UPDATE_FULL_TYPE=true when this changes the node's outputs to also
+  // update the node's full type information (if present).
+  public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
+                          @StdString BytePointer type_attr_name, @Cast("bool") boolean update_full_type);
+  public native @ByVal NativeStatus ShrinkTypeInfo(@Const @ByRef absl::flat_hash_map<int,int> index_mapping,
+                          @StdString String type_attr_name, @Cast("bool") boolean update_full_type);
+

**Comment by Craigacp** [comment]
So you've upgraded to TensorFlow v2.14.2 while keeping the Java code at v0.5.0? We have a few commits which did the Java side bits of the upgrade - https://github.com/tensorflow/java/commit/ac5c5601082c01a9b9f7cd696bf6575eca8d259b, but in general we recommend you stick to our published releases. Is there a reason you can't use 1.0.0-rc.2? 1.0.0 is coming very soon once we've figured out some javadoc issues in the deployment pipeline.

**Comment by lvsubbu** [comment]
Closing it.

**Comment by lvsubbu** [comment]
closing it

**Comment by lvsubbu** [comment]
this issue is fixed
