### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not find jnitensorflow in class, module, and library paths.

### ISSUE THREAD

**Issue by JeeDevUser** [tensorflow/java#586]
**System information**
- Windows 64bit
- TensorFlow installed from (source or binary): from binary
- TensorFlow version: 1.0.0-rc2
- Java version: 11
- Installed from Maven Central?: No
**Describe the problem**

```
import org.tensorflow.Graph;

public class TensorFlowTest {
   public static void main(String[] args) {
      try (Graph graph = new Graph()) {
         System.out.println("TensorFlow Java library is loaded successfully!");
      }
   }
}

```

at runtime, I am getting:

```
java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path ....
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
...
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnitensorflow in class, module, and library paths.
```

**Any other info / logs**
-Added following .jars in  the Java build path:
```
tensorflow-core-api-1.0.0-rc.2.jar
tensorflow-core-native-1.0.0-rc.2.jar
tensorflow-core-platform-1.0.0-rc.2.jar
javacpp-1.5.11.jar
javacpp-1.5.11-windows-x86_64.jar
ndarray-1.0.0.jar
protobuf-java-4.29.0-RC3.jar
```
What I am missing?

**Comment by Craigacp** [comment]
The platform jar is a meta jar that depends on the actual binaries. You need tensorflow-core-native-1.0.0-rc.2-windows-x86_64.jar as well which contains the actual TF Windows binary.

**Comment by JeeDevUser** [comment]
@Craigacp, thanks a lot...

**Comment by gabrielsaviank** [comment]
@Craigacp Any tips for Mac aarch64? I'm having the same issue. Even tried to create a test dockerfile with a unit test and got the same problem. I tried some workarounds I've opened docker console and tried 
`ls ~/.m2/repository/org/tensorflow/libtensorflow/2.11.0/linux-x86_64/libtensorflow.so` 
Returned nothing, then I installed 
`mkdir -p ~/.m2/repository/org/tensorflow/libtensorflow/2.11.0/linux-x86_64
curl -o ~/.m2/repository/org/tensorflow/libtensorflow/2.11.0/linux-x86_64/libtensorflow.so \
    https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-linux-x86_64-2.11.0.tar.gz`

Then I returned 
`libtensorflow.so` 

But when I try 

`mvn test -Djava.library.path=~/.m2/repository/org/tensorflow/libtensorflow/2.11.0/linux-x86_64`
 
and I get 
` UnsatisfiedLink no jnitensorflow in java.library.path: /usr/lib/jvm/java-17-amazon-corretto/lib/server:/usr/lib/jvm/java-17-amazon-corretto/lib:/usr/lib/jvm/java-17-amazon-corretto/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib` 

Perhaps there is nothing related, but I've checked and my docker image is using aarch64, later I'll try on linux on even on mac using x86 image.  

I'm using:
`<dependency>
    <groupId>org.tensorflow</groupId>
    <artifactId>tensorflow-core-platform</artifactId>
   <version>0.4.0</version>
</dependency>`

With java 17 corretto.
Thanks.

**Comment by Craigacp** [comment]
We support macos-aarch64 with `v1.0.0-rc.1` and up, and linux-aarch64 with `v1.0.0-rc.2` and up.
