### ISSUE TITLE
Advice needed: text summarization via a pre-trained model on a local computer

### ISSUE THREAD

**Issue by JeeDevUser** [tensorflow/java#587]
Hello everyone, I intend to do text summarization using some (any) pretrained model, which I would load from the local computer.

If something like this is possible, I am interested in:
- which model is suitable for that
- where can I download it from.
- how do I load it and do the summarization

Any help/online resource/... is welcome

**Comment by Craigacp** [comment]
There aren't many pretrained TF models for summarization on Hugging Face, and I think those models tend to be saved in Keras format anyway so will need converting into TF SavedModel format before they can be used with TF Java. I'd probably start with something like this - https://huggingface.co/google/flan-t5-large, but you could also use a decoder-only model (i.e. an LLM) though there aren't many of those in TF or Keras h5 format either (maybe Google's gemma model?). You'll need to load in the tokenizer (which for T5 is sentencepiece) and then tokenize the inputs, before passing them into TF-Java to get the output predicted token, loop it back around and keep predicting until you hit a termination condition (like `</s>` or a fixed token count).

To be honest, it might be simpler to use [jlama](https://github.com/tjake/Jlama/tree/main) or [llama3.java](https://github.com/mukel/llama3.java) and use a pre-trained llama 3 checkpoint. Those models are fairly good at summarization and the libraries already have tokenization and the token generation loop sorted which you'd need to implement on top of TF-Java. I don't think either of them support GPUs, so it depends how big your workload is in terms of batch size and latency.

**Comment by JeeDevUser** [comment]
@Craigacp, thanks for advice!

If I understand correctly, the tokenizer I would have to use is Sentencepiece (I would try with pegasus-xsum pretrained, but it uses the same tokenizer, so it doesn't matter) in order to tokenize inputs.

At this moment, I generate the savedModel format from the pagesus-xsum model (=got the .pb and/variables files etc....)

Now I wonder, if TensorFlow Java API  supports SentencePiece somehow or not?
Maybe the question doesn't make sense (I'm still new to this) - mainly, is there a way to somehow use this tokenizer kind of tokenizer for tokenization... I want to avoid any dependency on Python in the runtime, so I'm only interested in a pure Java implementation...huh?

**Comment by JeeDevUser** [comment]
...and, for example, DeepJavaLibrary (DJL) have the [Sentencepice implementation:](https://github.com/deepjavalibrary/djl/blob/master/extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java)
I wonder, could I use it to tokenize input, before passing them to TF Java?

**Comment by Craigacp** [comment]
You can put the sentencepiece op from tensorflow-text into a TF graph, but that is a bit of a pain to do from Java and will require you to understand how TF works on a deeper level. Otherwise DJL's wrapper should be fine, and there are others available. You'll still need to write the generative loop yourself, passing in the input tokens, the previously generated tokens and the key-value cache, then building a sampling mechanism.

**Comment by JeeDevUser** [comment]
thanks @Craigacp, I made some progress, by using DJL Sentencepiece implementation, over TF SavedModel format I made. I successfully tokenized the input text. But I got stuck with what you said:

> You'll still need to write the generative loop yourself, passing in the input tokens, the previously generated tokens and the key-value cache, then building a sampling mechanism.

- here is relevant part of code:

```
         String text = "This is an example text for summarization.";
         int[] intTokens = spProcessor.encode(text); // DJL Sentencepiece
         System.out.println("Tokens: " + Arrays.toString(intTokens));

         // Converting tokens into  TInt32 Tensor
         IntNdArray intData = NdArrays.ofInts(Shape.of(1, intTokens.length));
         for (int i = 0; i < intTokens.length; i++) {
            intData.setInt(intTokens[i], 0, i);
         }
         // so far, so good... now:
     try (TInt32 loopInputTensor = Tensor.of(TInt32.class, Shape.of(1, intTokens.length), intData::copyTo)) {         
            // 2.TF SavedModel loading:
            String modelPath = "d:/Install/TensorFlow/models/pegasus_xsum/saved_model";
            SavedModelBundle model = SavedModelBundle.load(modelPath, "serve");
            System.out.println("The saved Model successfully loaded!");

            // 3. getting the name of input and output tensors:
            SignatureDef signatureDef = model.metaGraphDef().getSignatureDefOrThrow("serving_default");
            String inputTensorName = signatureDef.getInputsOrThrow("input_ids").getName();
            String outputTensorName = signatureDef.getOutputsOrThrow("logits").getName();
            
             // 4. starting the inference:
            try (Tensor outputTensor = model.session().runner()
                     .feed(inputTensorName, loopInputTensor)
                     .fetch(outputTensorName)
                     .run().get(0)) {
                     // ---- I'M STUCK HERE, I DON'T KNOW WHAT TO DO...any help?!?
             }        
         }
         

```

**Comment by Craigacp** [comment]
The output of the model will be a probability distribution over tokens. The simplest thing is to do "greedy decoding", where you pick the most likely token (i.e. the one with the highest probability), then you append that token id to your input tokens and run inference again.

**Comment by JeeDevUser** [comment]
further analysis shows:

 ```
                             float maxProbability = Float.NEGATIVE_INFINITY;
                              int predictedToken = -1;

                              for (int i = 0; i < vocabSize; i++) {
                                 float probability = thelogits.getFloat(0, currentDecoderInput.length - 1, i);

                                 if (probability > maxProbability) {
                                    maxProbability = probability;
                                    predictedToken = i;
                                 }
                              }
                              System.out.println("maxProbability = " + maxProbability + ",predictedToken = " + predictedToken);

```
I am getting following output:

```
maxProbability = 3.7507553,predictedToken = 52197
maxProbability = 7.6098137,predictedToken = 52197
maxProbability = 7.422515,predictedToken = 52197
maxProbability = 7.29151,predictedToken = 52197
maxProbability = 7.1766005,predictedToken = 52197
maxProbability = 7.0959473,predictedToken = 52197
maxProbability = 7.01433,predictedToken = 52197
maxProbability = 6.944235,predictedToken = 52197
maxProbability = 6.8965693,predictedToken = 52197
maxProbability = 6.8409863,predictedToken = 52197
maxProbability = 6.804291,predictedToken = 52197
maxProbability = 6.7720375,predictedToken = 52197
maxProbability = 6.7398033,predictedToken = 52197
maxProbability = 6.7057004,predictedToken = 52197
maxProbability = 6.678092,predictedToken = 52197
maxProbability = 6.651373,predictedToken = 52197
maxProbability = 6.6312737,predictedToken = 52197
```
The predicted token id always 52192 (=PPT)
Wondering why?

**Comment by Craigacp** [comment]
It depends how the model is exported. If it came from HuggingFace then they typically prefer that models are supplied with the key value cache and get confused if you don't supply it. I've not tried to use an encoder decoder model for generation in bare TF before, so I'm not sure how to exactly format the inputs. Where did you get the pegasus-xsum checkpoint?

Once you get this working it should be possible to make it more efficient by using the ndarray functions which load a complete array, by making a larger buffer that you can write to, and also you don't need to write in the encoder data each time but I'm not sure where the bug is in your current code.

**Comment by JeeDevUser** [comment]
Hey @ Craigacp , thanks for suggestion, I made a new progress ;-)

> Where did you get the pegasus-xsum checkpoint?
-Good point! I just downloaded the relevant pagesus-xsum files from
https://huggingface.co/google/pegasus-xsum/tree/main
under 'Files and versions' section:
```
tf_model.h5
spiece.model
generation_config.json
config.json
```
-them I used floowing Python script in order to convert  to savedModel format:

```
import tensorflow as tf
from transformers import TFAutoModelForSeq2SeqLM

# Path to the files in local disk
model_path = "d:/Install/TensorFlow/models/pegasus_xsum/"
h5_model_path = f"{model_path}tf_model.h5"
saved_model_path = f"{model_path}saved_model"

# reconstruc model by using conf and weights
model = TFAutoModelForSeq2SeqLM.from_pretrained(model_path, from_pt=False)

# Save reconstructed model into SavedModel format:
tf.saved_model.save(model, saved_model_path)

print(f"SavedModel saved to the location: {saved_model_path}")

```
This way, I got:
```
/assests
/variabled
saved_model.pb
fingerprint.pb
```
-Now, I got the following output:

```
maxProbability = 10.652109,predictedToken = 139
maxProbability = 9.474838,predictedToken = 6442
maxProbability = 12.907925,predictedToken = 131
maxProbability = 14.232979,predictedToken = 116
maxProbability = 11.341987,predictedToken = 1578
maxProbability = 14.993374,predictedToken = 111
maxProbability = 17.715422,predictedToken = 552
maxProbability = 16.267975,predictedToken = 21089
.....
```
-as you can see, the predicted token is always different, and for the input string:
`"The sun was setting behind the mountains, casting a warm golden glow over the valley. As the sky turned shades of pink and orange, the air grew cooler, and the sounds of nature became more pronounced. Birds chirped softly in the distance, signaling the end of the day. People gathered along the riverbank to enjoy the peaceful scene, taking in the beauty of the moment. It was a perfect end to a long, busy day, offering a sense of tranquility and calm.";
`
I got following summary:
`Summarized Text: day pasta good these tree us American stakeholder ban Perse photos then – treeAnd –danre – demands well
`
:-) )) ..!

This isn't right, but I'm making some progress.
Now, question:
1. take look at my pytnoh script for savedModel convert.
Is there a better way? Becase of, durrng execution, I got the message:

```
Some layers of TFPegasusForConditionalGeneration were not initialized from the model checkpoint at d:/Install/TensorFlow
/models/pegasus_xsum/ and are newly initialized: ['final_logits_bias']
```

2. you are mention:
> If it came from HuggingFace then they typically prefer that models are supplied with the key value cache and get confused if you don't supply it

-Do you know, where can I get information about this?

**Comment by JeeDevUser** [comment]
Finally!
I got the text summarization by using pretrained T5-base model!
@Craigacp , thank you for your help, your advice meant a lot to me.
