### ISSUE TITLE
Graph importGraphDef doesn't match documentation

### ISSUE THREAD

**Issue by Ben-Epstein** [tensorflow/java#60]
In the TF java [documentation ](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Graph#importGraphDef(byte[])) It looks as if you can import a Graph Defition from a byte array. In their [examples](https://github.com/tensorflow/tensorflow/blob/d4c048beee1bb8a494c4de4675ee009fd79283a2/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java#L112) they also read from a byte array.

The code here, however, requires a [GraphDef](https://github.com/tensorflow/java/blob/0f0ff7d10fafe2c42ea4768ec13ab5a169da1ce5/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Graph.java#L149).

What's the best way to overcome this? Or am I not understanding what a GraphDef is?

Thanks!

**System information**
- TensorFlow version: 0.1.0-SNAPSHOT (2.2.0)

**Comment by karllessard** [comment]
The legacy version of TF Java (as pointed by your documentation) does not include the protobuf classes automatically and you need to depend on `org.tensorflow:proto` to access and serialize them. 

The new version is more convenient as the proto classes (like `GraphDef`) are already provided, thus you should use it directly and not go through this unnecessary serialization. 

In other words, the new method accepting `GraphDef` as a parameter is safer than the old one accepting the serialized version of this proto class as a raw byte array.

**Comment by Ben-Epstein** [comment]
@karllessard thanks for the reply. 

I'm not seeing in the documentation an example of using a GraphDef. Can you point me to an example of creating a GraphDef that I can then pass into the importGraphDef function?

**Comment by karllessard** [comment]
@Ben-Epstein , I can probably find an example for this, yes, but before doing it, is there any reason why you can't use a [`SavedModelBundle`](https://github.com/tensorflow/java/blob/eeb67786b2d142bedc6975a0ad092218cac2ded4/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/SavedModelBundle.java#L45) instead? 

While still being supported, `GraphDef` protobuf is the "legacy" format for saving TF models and have been replaced by the [saved model](https://www.tensorflow.org/guide/saved_model) format. You can load a saved model just by providing the path of the saved model directory:

```java
try (SavedModelBundle bundle : SavedModelBundle.load("path/to/saved/model", "serve")) {
    Graph graph = bundle.graph();
    ... 
}

**Comment by Ben-Epstein** [comment]
@karllessard I would much prefer to use a SavedModelBundle, but I can't find a load function that takes a ByteStream. In production I'll be receiving the model from a remote location and writing to disk before reading adds unnecessary IO so I was trying to avoid it. 

Is there a way that I missed that would allow me to use a SavedModelBundle to load a ByteStream?

**Comment by karllessard** [comment]
Mmh, if you are receiving a stream of bytes, then I guess your model was saved as a `GraphDef`. What do you mean exactly by `ByteStream`, a simple Java `InputStream`? 

If so, then you can probably do something like:
```java
try (Graph g = new Graph()) {
    g.importGraphDef(GraphDef.parseFrom(inputStream));
    ...
}
```

**Comment by Ben-Epstein** [comment]
When I say ByteStream I meant generally a stream of bytes. What I'm actually receiving is going to be a serialized model either from a .pb or .h5 (ideally h5 if there is Keras loading support, although I didn't see any in the Keras dir).

That code is helpful, thank you. I may open a different issue regarding loading an h5 file from Keras, unless you have a quick pointer to it available.

**Comment by karllessard** [comment]
We don't support (yet) loading hdf5 models directly to TF Java. I've already used [this script](https://github.com/amir-abdi/keras_to_tensorflow) in the past to convert the `.h5` model to `.pb` and it worked pretty well.

Also, you can forget my previous comment about the `GraphDef` format being legacy, it looks like this format is still being used when exporting a saved model.

**Comment by Ben-Epstein** [comment]
I think I tried that script and had issues on tf 2.2 but I think that's out of scope of this post. Thanks for all of the help!
