### ISSUE TITLE
Add option to run TensorFlow job on the preferred device

### ISSUE THREAD

**Issue by zaleslaw** [tensorflow/java#77]
**System information**
- TensorFlow version (you are using): 1.15 or 2.x
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Now, we could run our code on GPU only via adding GPU dependencies to the classpath.
But the basic Python API [provides an ability](https://www.tensorflow.org/api_docs/python/tf/device) to set up the preferred device (GPU or CPU via device name) 

The basic option also is available for low-level builder [here](https://github.com/tensorflow/java/blob/3062c14be0713be554015e257e30e7547abf711c/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/OperationBuilder.java#L90)

**Will this change the current api? How?**

Let's add the function `tf.withDevice(“/GPU:0”)` to the `Scope` class.

**Who will benefit with this feature?**
Anyone who trains neural network in distributed mode on different GPU/CPU devices.

**Any Other info.**

**Comment by karllessard** [comment]
Sounds good @zaleslaw ! 

I suggest that we go with a better typed API, maybe using some sort of enum, instead of hardcoded string like this (e.g. something like `tf.withDevice(Device.GPU)` or `tf.withDevice(Device.GPU, 1)`, etc. Anyhow, something we can define together as we go, wdyt?

**Comment by zaleslaw** [comment]
I'm not very familiar with all possible device id strings, but it sounds
good for me.

пн, 22 июн. 2020 г. в 17:32, Karl Lessard <notifications@github.com>:

**Comment by Craigacp** [comment]
I'm in favour of an enum, and then an optional device ID number. We'll need it to specify what GPU something runs on, and I use shared GPU resources so I need to not contend with other users on different GPUs.

**Comment by zaleslaw** [comment]
Agree with Adam here: GPU/CPU mode with optional String IDs

пн, 22 июн. 2020 г. в 18:43, Adam Pocock <notifications@github.com>:

**Comment by karllessard** [comment]
Yes, that was my proposal as well. I just want to make sure that we are not missing anything, I don't know if TensorFlow supports more options than simply "/<device>:<id>" in their string format, can you please double check @zaleslaw ?

**Comment by saudet** [comment]
The string also accepts host names and a lot of other things we'll have problems fitting in just enums:
https://www.tensorflow.org/guide/gpu
https://www.tensorflow.org/guide/tpu

**Comment by karllessard** [comment]
So probably some kind of builder could be more appropriate then? e.g. `Device.job("localhost").replica(0).task(0).gpu(1)`

**Comment by hthu** [comment]
Drive by comment.

Maybe look into existing python class?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/device_spec.py

**Comment by hthu** [comment]
I'm sending https://github.com/tensorflow/java/pull/83 for getting the DeviceSpec ported as a start.

**Comment by aday00** [comment]
Great idea!  Happy to help test this with a multi-GPU system (#131).

Additional question: is there a command-line option to java to explicitly select which GPU should be used?  GPU 0 is selected by default, but my system has 4 GPUs, so I'd like to run 4 java processes at once, with each java process explicitly selecting a different GPU.

**Comment by aday00** [comment]
> Additional question: is there a command-line option to java to explicitly select which GPU should be used?

As expected, the CUDA_VISIBLE_DEVICES environment variable may be used to select GPU 1, for instance:
```
# export CUDA_VISIBLE_DEVICES=1; nice java -jar my.jar ...
```

**Comment by zaleslaw** [comment]
@aday00 and @karllessard looks like we have working device spec now, but have no ability to apply it for our graph or model (we have only setDevice option in GraphBuilder, but we could not pass it through the current TF operands and as a result we have no control on device yet.)

Please, correct me if I'm wrong.

**Comment by zaleslaw** [comment]
Maybe in eager mode it's better move to runner, but for the static graph look like we need to pre-define it earlier

**Comment by zaleslaw** [comment]
Yet one problem with imported graphs and models. When and how we could bind the device spec? Maybe after import we should have a method on graph, like addGradients? But in reality we need to rebuild our graph with new device specs.

**Comment by karllessard** [comment]
Hey @zaleslaw , we should probably add the ability to add the `DeviceSpec` to the `Scope` when building an operation, similar to what we do with the operation [name](https://github.com/tensorflow/java/blob/e181d03fa472823473e203d13b9f6e0249255b5a/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/op/Scope.java#L123). 

So we can end up doing something like:

`tf.withName("myOp").withDevice(DeviceSpec.newBuilder()...).nn.avgPool(...)`

If you feel that the syntax for building a device spec can still be improved, feel free to update it, thanks!

**Comment by karllessard** [comment]
The reason for doing it at the scope level is to limit the number of operation factories, otherwise you will double-up the number of endpoints we have in the `Ops` classes (where one factory method = one endpoint). So instead of having 1000+ endpoints, we'd have now 2000+ endpoints :)

**Comment by zaleslaw** [comment]
I agree, that 2000 endpoints instead of 1000 is not so good, but the main idea of op device API has a very fine and detailed control over where operations are performed.
Scope is too high and does not give that degree of control

**Comment by zaleslaw** [comment]
Could you please explain what is the problem with endpoints increasing? Maybe I miss something in performance or this framework development?

**Comment by Craigacp** [comment]
Well at some point we'll run out of space in the class file.

**Comment by saudet** [comment]
> Well at some point we'll run out of space in the class file.

I'd like to see that. Check what it looks like for MKL and it's still fine:
https://github.com/bytedeco/javacpp-presets/blob/master/mkl/src/gen/java/org/bytedeco/mkl/global/mkl_rt.java

**Comment by karllessard** [comment]
Like we discussed during the call today, my main concern of adding a new factory, and therefore duplicate all ops endpoints, is the noise that will create in the IDE's auto-suggest feature, plus the fact that `Scope` was especially designed to handle this case.

**Comment by aday00** [comment]
Excited to see this feature develop!
Will ```tf.withName("myOp").withDevice(DeviceSpec.newBuilder()...).nn.avgPool(...)``` allow different parts of a neural network to be trained on different GPUs simultaneously?
May some parts of the neural networks be trained on CPU and other parts on GPU?
Happy to test this as well, when appropriate.

**Comment by zaleslaw** [comment]
I'll experiment with different modes. But I agree that it could be useful
to make backprop and multiple matrices on different GPUs for different
branches in models like InceptionV3 and so on.

пн, 2 нояб. 2020 г. в 05:09, aday00 <notifications@github.com>:

**Comment by aday00** [comment]
Sounds great @zaleslaw!  For me, the models become so large that 1 GPU and 12GB GPU RAM is not enough to hold the entire model.  Partitioning the model across 2 or more GPUs in a computer would make larger models work.
