### ISSUE TITLE
Is it possible to build the libtensorflow first?

### ISSUE THREAD

**Issue by GerScau** [tensorflow/java#81]
**System information**
- TensorFlow version (you are using):  tf2.0+
- Are you willing to contribute it (Yes/No): yes.. but my code is bad

**Describe the feature and the current behavior/state.**

It's so said i have been told that "There is no libtensorflow support for TensorFlow 2 yet"
[https://github.com/tensorflow/tensorflow/issues/36950#issuecomment-592238340](url)

tf2 changes a lot, we could not use the new model build on tf2 due to no new version of libtensorflow available.

**Will this change the current api? How?**

To build the whole tf2 on java is huge project, is it possible to build the libtensorflow first?

**Who will benefit with this feature?**

all developer useing tf java api

**Comment by saudet** [comment]
Yes, that's what the snapshots are for. Make sure you're building with `mvn -Pdev ...`

**Comment by MilanCugur** [comment]
@saudet 

Can you provide .jar for download?

**Comment by saudet** [comment]
Sure, they are all available here: https://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/

**Comment by GerScau** [comment]
> Sure, they are all available here: https://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/

some queustion:
1. i check the jars and find codes like Session and Graph. It seems session and graph is deprecated in tf2, so i wonder if these snapshot is working for tf2... Mainly because there is no documentation
2. Is any plan for keras lib?
I’m sorry to have put forward so many demands, but there are really urgent needs for these functions

**Comment by saudet** [comment]
For questions, please use the mailing list or the Gitter channel, if possible. Thanks!

/cc @karllessard

**Comment by GerScau** [comment]
try mailing
