### ISSUE TITLE
Snapshot libtensorflow-1.0.1-20170323.012702-1.jar cannot find packages

### ISSUE THREAD

**Issue by MilanCugur** [tensorflow/java#84]
With your snapshot **libtensorflow-1.0.1-20170323.012702-1.jar** (Downloaded from https://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/libtensorflow/1.0.1-SNAPSHOT/) get the errors like: 

(command:
`javac -cp ./libtensorflow-1.0.1-20170323.012702-1.jar:. HelloTensorFlowSnapshot.java`
)

```
HelloTensorFlowSnapshot.java:4: error: package org.tensorflow.exceptions does not exist
import org.tensorflow.exceptions.TensorFlowException;
                                ^
HelloTensorFlowSnapshot.java:9: error: cannot find symbol
import org.tensorflow.GraphOperation;
                     ^
  symbol:   class GraphOperation
  location: package org.tensorflow
HelloTensorFlowSnapshot.java:10: error: package org.tensorflow.proto.framework does not exist
import org.tensorflow.proto.framework.SignatureDef;
                                     ^
HelloTensorFlowSnapshot.java:14: error: package org.tensorflow.proto.framework does not exist
import org.tensorflow.proto.framework.MetaGraphDef;
                                     ^
HelloTensorFlowSnapshot.java:16: error: package org.tensorflow.proto.framework does not exist
import org.tensorflow.proto.framework.TensorInfo;
                                     ^
HelloTensorFlowSnapshot.java:17: error: package org.tensorflow.types does not exist
import org.tensorflow.types.TFloat32;
                           ^
HelloTensorFlowSnapshot.java:18: error: package org.tensorflow.tools does not exist
import org.tensorflow.tools.Shape;
                           ^
HelloTensorFlowSnapshot.java:20: error: package org.tensorflow.tools.buffer does not exist
import org.tensorflow.tools.buffer.DataBuffers;
                                  ^
HelloTensorFlowSnapshot.java:21: error: package org.tensorflow.tools.ndarray does not exist
import org.tensorflow.tools.ndarray.FloatNdArray;
                                   ^
HelloTensorFlowSnapshot.java:22: error: package org.tensorflow.tools.ndarray does not exist
import org.tensorflow.tools.ndarray.StdArrays;
                                   ^
HelloTensorFlowSnapshot.java:23: error: package org.tensorflow.proto.framework does not exist
import org.tensorflow.proto.framework.TensorInfo;

```

I try to run the working code from https://stackoverflow.com/questions/61228372/tensorflow-2-0-java-api.

Thanks in advance,
Milan

**Comment by saudet** [comment]
Please use a build tool like Maven or Gradle. Don't try to use the JAR files manually.

**Comment by karllessard** [comment]
Hi @MilanCugur , 

you are trying to use an old artifact from the 1.x generation of TFJava (`org.tensorflow:libtensorflow` is legacy stuff). 

Please read carefully that [readme page](https://github.com/tensorflow/java). Our artifact are now named `org.tensorflow:tensorflow-core-*` and we are now at version 0.2.0-SNAPSHOT. 

Let me know if you still have any issue, thanks,
Karl

**Comment by MilanCugur** [comment]
@karllessard 

Karl, thank you a lot for such a fast and a detailed response. 

I have successfully built your project, by using mentioned snapshots. 

Are there any way to get **libtensorflow** and **jni** jars like the one on the official page: https://www.tensorflow.org/install/lang_java (that can be used via classpath forwarding, and not to use maven like includings into my projects?)

**Comment by karllessard** [comment]
libtensorflow and jni are artifacts that were distributed during TensorFlow
1.x and are considered deprecated.

You can still use them if you want (no need to fetch snapshots in this case
as they have been released a long time ago) but you cannot mix them with
the artifacts that are distributed by this SIG based on TF2.x, which are
not compatible.

- Karl

**Comment by MilanCugur** [comment]
@karllessard 
Karl, 

Thank you once again. 
I have successfully built up your project and integrate it into the my current environment. 
Everything is working just perfect! Great job! 

We can close this issue. 

All the best,
Milan

**Comment by saudet** [comment]
> @karllessard
> 
> Karl, thank you a lot for such a fast and a detailed response.
> 
> I have successfully built your project, by using mentioned snapshots.
> 
> Are there any way to get **libtensorflow** and **jni** jars like the one on the official page: https://www.tensorflow.org/install/lang_java (that can be used via classpath forwarding, and not to use maven like includings into my projects?)

Yes, of course it's possible. We just need to update these instructions to reflect the new names of the JAR files.
However, it's much easier to use a build tool like Maven or Gradle anyway...
